const mongoose=require('mongoose'),family=require('../services/familyAccess.service'),asyncHandler=require('../utils/asyncHandler'),AppError=require('../utils/AppError'),{ok}=require('../utils/apiResponse');
const {encrypt}=require('../utils/encryption');
const Private=require('../models/ParentPrivateProfile');
function parent(req){if(!(req.accessibleRoles||req.user.roles||[]).includes('parent'))throw new AppError('Parent role required.',403);}
const view=row=>({bankName:row?.bankName||'',accountTitle:row?.accountTitle||'',accountLast4:row?.accountLast4||'',notes:row?.notes||''});
const get=asyncHandler(async(req,res)=>{parent(req);return ok(res,view(await Private.findOne({user:req.user._id})));});
const save=asyncHandler(async(req,res)=>{parent(req);const b=req.body;for(const key of ['bankName','accountTitle','accountNumber','notes'])if(b[key]!==undefined&&typeof b[key]!=='string')throw new AppError('Use text values for private details.',422);if(String(b.notes||'').length>10000||String(b.accountTitle||'').length>150||String(b.bankName||'').length>150)throw new AppError('Private details exceed the allowed length.',422);const set={};for(const key of ['bankName','accountTitle','notes'])if(b[key]!==undefined)set[key]=b[key].trim();if(b.accountNumber!==undefined){const value=b.accountNumber.replace(/\s/g,'');if(value&&!/^[A-Za-z0-9-]{4,40}$/.test(value))throw new AppError('Use a valid account number or IBAN.',422);set.accountNumberEncrypted=value?encrypt(value):'';set.accountLast4=value.slice(-4);}const row=await Private.findOneAndUpdate({user:req.user._id},{$set:set},{upsert:true,new:true,runValidators:true});return ok(res,view(row));});
const adminSummary=asyncHandler(async(req,res)=>{
 if(!(req.user.roles||[]).some(r=>['super_admin','admin','platform_staff'].includes(r)))throw new AppError('Administration permission required.',403);
 if(req.user.roles.includes('platform_staff')&&!req.permissions?.includes('complaint:manage'))throw new AppError('Administration reporting permission required.',403);
 const users=await require('../models/User').find({roles:'parent'}).select('_id status lastLoginAt');const ids=users.map(u=>u._id);const Link=require('../models/ParentChildLink');
 const [linkStats,meetings,feedback,complaints,consents,payments]=await Promise.all([
 Link.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),require('../models/ParentTeacherMeeting').aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),require('../models/InstitutionFeedback').aggregate([{$match:{fromUser:{$in:ids}}},{$group:{_id:null,average:{$avg:'$rating'},count:{$sum:1}}}]),require('../models/Complaint').countDocuments({submittedBy:{$in:ids},status:{$in:['open','in_review']}}),require('../models/ParentPermission').aggregate([{$group:{_id:'$decision',count:{$sum:1}}}]),require('../models/FamilyWalletSettlement').aggregate([{$group:{_id:'$currency',paid:{$sum:'$amount'},payments:{$sum:1},refunded:{$sum:{$cond:[{$ifNull:['$refundedAt',false]},'$amount',0]}}}}])
 ]);return ok(res,{parents:users.length,activeAccounts:users.filter(u=>u.status==='active').length,activeLast30Days:users.filter(u=>u.lastLoginAt&&u.lastLoginAt>new Date(Date.now()-30*86400000)).length,connections:linkStats,meetings,schoolSatisfaction:feedback[0]||{average:null,count:0},openComplaints:complaints,consents,walletPayments:payments});
});
module.exports={get,save,adminSummary};
