// Actual protected HTTP APIs + React panels, using disposable data. No live account involved.
const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict'),{spawn}=require('child_process');
const r=require('module').createRequire('D:/Career-Z-backend/package.json');process.env.NODE_ENV='test';process.env.DISABLE_SUBSCRIPTION_LIMITS='true';
const mongoose=r('mongoose'),{MongoMemoryReplSet}=r('mongodb-memory-server'),express=r('express'),jwt=r('jsonwebtoken');
const notification=r('./src/services/notification.service');notification.notify=async()=>{};notification.notifyParentsOfStudent=async()=>{};
const model=n=>r('./src/models/'+n);
(async()=>{let db,server,chrome,ws;
 try{
 db=await MongoMemoryReplSet.create({replSet:{count:1}});await mongoose.connect(db.getUri());console.log('Temporary browser database ready');
 const users={};for(const [name,role] of [['Parent','parent'],['Student','student'],['Teacher','teacher'],['Owner','institution_owner']]){const user=await model('User').create({fullName:name+' Browser Test',email:name.toLowerCase()+'@browser.local',passwordHash:'x',roles:[role]});users[name]=user;await model('RoleRequest').create({user:user._id,requestedRole:role,status:'approved'});await model('UserProfile').create({user:user._id,role,completed:true,percent:100});}
 const school=await model('Institution').create({name:'Browser School',slug:'browser-school',type:'school',country:'PK',owner:users.Owner._id,verificationStatus:'approved'});
 await model('StudentProfile').create({user:users.Student._id,primaryInstitution:school._id,rollNumber:'B-01'});
 const course=await model('Course').create({title:'Browser Math',teacher:users.Teacher._id,institution:school._id,isFree:true,published:true});await model('Enrollment').create({course:course._id,student:users.Student._id,status:'active'});
 const link=await model('ParentChildLink').create({parent:users.Parent._id,student:users.Student._id,requestedBy:users.Student._id,status:'pending'});
 const app=express();app.use(r('cors')());app.use(express.json());app.use('/api',r('./src/routes/index'));app.use((e,req,res,next)=>res.status(e.statusCode||500).json({message:e.message}));server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 const base='http://127.0.0.1:'+server.address().port;console.log('Isolated authenticated API ready');
 const token=user=>jwt.sign({sub:String(user._id)},r('./src/config/env').jwt.accessSecret,{expiresIn:'10m'});
 const port=19392;chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--no-first-run','--disable-gpu','--remote-debugging-port='+port,'--user-data-dir='+fs.mkdtempSync(path.join(os.tmpdir(),'cz-parent-')),'about:blank'],{windowsHide:true,stdio:'ignore'});
 let targets;for(let n=0;n<40;n++){try{targets=await(await fetch('http://127.0.0.1:'+port+'/json')).json();break;}catch{await new Promise(resolve=>setTimeout(resolve,250));}}
 if(!targets)throw Error('Headless Chrome did not start');ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;setTimeout(()=>reject(Error('Chrome socket timeout')),10000).unref();});console.log('Headless browser ready');let seq=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')console.error('Browser exception:',m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')console.error('Browser console:',m.params.args.map(a=>a.value||a.description).join(' '));if(m.id){pending.get(m.id)?.(m.result);pending.delete(m.id);}};const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++seq,resolve);ws.send(JSON.stringify({id:seq,method,params}));setTimeout(()=>reject(Error('Browser command timeout: '+method)),15000).unref();});
 async function evaluate(expression){const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.text+' '+JSON.stringify(result.exceptionDetails.exception?.description));return result.result.value;}
 await call('Runtime.enable');await call('Page.navigate',{url:'http://localhost:5173/about'});await new Promise(resolve=>setTimeout(resolve,2500));
 await evaluate(`window.__familyFetch=window.fetch.bind(window);window.fetch=(url,options)=>window.__familyFetch(typeof url==='string'&&url.includes('/api/')?${JSON.stringify(base)}+'/api/'+url.split('/api/')[1]:url,options);document.querySelector('#root').style.display='none';const container=document.createElement('div');container.id='family-test';container.style.padding='16px';document.body.appendChild(container);window.__flashes=[];`);
 async function mount(component,user,props={},module='FamilyCenter.jsx'){await evaluate(`(async()=>{const React=await import('/node_modules/.vite/deps/react.js');const DOM=await import('/node_modules/.vite/deps/react-dom_client.js');const panels=await import('/src/components/dashboard/'+${JSON.stringify(module)});localStorage.setItem('cz_access_token',${JSON.stringify(token(user))});localStorage.setItem('cz_user',${JSON.stringify(JSON.stringify(user.toSafeJSON()))});window.__familyRoot?.unmount();window.__familyRoot=(DOM.createRoot||DOM.default.createRoot)(document.querySelector('#family-test'));window.__familyRoot.render((React.createElement||React.default.createElement)(panels[${JSON.stringify(component)}],{...${JSON.stringify(props)},onFlash:(m)=>window.__flashes.push(m)}));})()`);await new Promise(resolve=>setTimeout(resolve,900));return evaluate('document.querySelector("#family-test").innerText');}
 let text=await mount('FamilyConnections',users.Parent);assert(text.includes('Student Browser Test')&&text.includes('pending'),text);
 await evaluate(`[...document.querySelectorAll('#family-test button')].find(b=>b.textContent==='Approve').click()`);await new Promise(resolve=>setTimeout(resolve,800));assert.equal((await model('ParentChildLink').findById(link._id)).status,'approved');console.log('PASS parent approves student invitation from browser');
 text=await mount('FamilyConnections',users.Student,{student:true});assert(text.includes('Parent Browser Test')&&text.includes('Health access'),text);console.log('PASS student guardian list and permissions');
 const request=await model('FamilyConsentRequest').create({institution:school._id,student:users.Student._id,createdBy:users.Owner._id,type:'trip',title:'Science trip'});
 text=await mount('InstitutionFamilyActions',users.Owner);assert(text.includes('Science trip')&&text.includes('Awaiting guardian response'),text);assert.equal(await evaluate(`document.querySelector('#family-test select[required]').options.length`),2);console.log('PASS institution roster selector and request inbox');
 text=await mount('FamilyTeacherNotes',users.Teacher);assert(text.includes('Student Browser Test')&&text.includes('Browser Math'),text);console.log('PASS teacher child-scoped notes roster');
 await model('FamilyObservation').create({institution:school._id,student:users.Student._id,actor:users.Teacher._id,type:'progress',text:'Practice fractions daily'});
 await model('Attendance').create({date:new Date(),markedBy:users.Teacher._id,records:[{student:users.Student._id,status:'half_day'}]});
 await model('Result').create({student:users.Student._id,institution:school._id,course:course._id,subject:'Math',marksObtained:42,totalMarks:50,recordedBy:users.Teacher._id,term:'Term 1'});
 text=await mount('FamilyAcademic',users.Parent,{kind:'performance'});assert(text.includes('Practice fractions daily')&&text.includes('84%')&&text.includes('half day'),text);console.log('PASS real attendance, marks and teacher feedback rendering');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await new Promise(resolve=>setTimeout(resolve,200));assert(await evaluate(`document.documentElement.scrollWidth<=document.documentElement.clientWidth+1`),'Mobile view overflows');const screenshot=await call('Page.captureScreenshot',{captureBeyondViewport:true});fs.writeFileSync('audit/parent-performance-mobile.png',Buffer.from(screenshot.data,'base64'));console.log('PASS 390px mobile layout');
 text=await mount('FamilyAcademic',users.Parent,{kind:'permissions'});assert(text.includes('Science trip'),text);
 console.log('PASS guardian permission inbox');
 await evaluate(`document.querySelector('#family-test input[placeholder="Your full name"]').value='Parent Browser Test'`).catch(()=>{});
 const downloads=fs.mkdtempSync(path.join(os.tmpdir(),'cz-parent-pdf-'));await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
 text=await mount('FamilyAcademic',users.Parent,{kind:'results'});await evaluate(`[...document.querySelectorAll('#family-test button')].find(b=>b.textContent.includes('Download report card')).click()`);
 const pdf=path.join(downloads,'report-card.pdf');for(let n=0;n<30;n++){if(fs.existsSync(pdf))break;await new Promise(resolve=>setTimeout(resolve,300));}assert(fs.existsSync(pdf),'PDF download missing');assert.equal(fs.readFileSync(pdf).subarray(0,4).toString(),'%PDF');fs.mkdirSync('audit/parent-downloads',{recursive:true});fs.copyFileSync(pdf,'audit/parent-downloads/report-card.pdf');console.log('PASS actual branded report-card PDF download');
 text=await mount('FamilyPrivate',users.Parent,{},'FamilyPrivate.jsx');assert(text.includes('Private notes and bank details'),text);console.log('PASS parent private details interface');
 text=await mount('FamilyPolicy',users.Owner,{},'FamilyPolicy.jsx');assert(text.includes('Persistent absence warning threshold'),text);console.log('PASS institution guardian support policy');
 text=await mount('StudentFamilyMeeting',users.Student,{},'FamilyPolicy.jsx');assert(text.includes('Teacher Browser Test'),text);console.log('PASS student real-teacher meeting invitation');
 await model('Wallet').create({user:users.Parent._id,currency:'PKR',available:1000});await model('CafeteriaItem').create({institution:school._id,name:'Browser lunch',price:100,currency:'PKR',stock:2,active:true,allergens:'Contains wheat'});
 text=await mount('default',users.Parent,{},'FamilyCafeteria.jsx');assert(text.includes('Browser lunch')&&text.includes('Contains wheat'),text);await evaluate(`[...document.querySelectorAll('#family-test button')].find(b=>b.textContent==='Pay PKR 100.00').click()`);await new Promise(resolve=>setTimeout(resolve,1000));const order=await model('CafeteriaOrder').findOne();assert(order,'Browser purchase not saved');assert.equal((await model('Wallet').findOne({user:users.Parent._id})).available,900);console.log('PASS actual parent cafeteria purchase from browser');
 text=await mount('default',users.Student,{studentId:String(users.Student._id)},'FamilyCafeteria.jsx');assert(text.includes(order.pickupCode),text);console.log('PASS student cafeteria pickup code');
 text=await mount('default',users.Owner,{institution:true},'FamilyCafeteria.jsx');assert(text.includes('Confirm child’s pickup code'),text);console.log('PASS institution cafeteria collection interface');
 await model('Fee').create({student:users.Student._id,institution:school._id,title:'Browser tuition',amount:300,currency:'PKR',recordedBy:users.Owner._id});await model('FamilyWalletSettlement').init();await model('FamilyPlatformBalance').init();
 text=await mount('FamilyPayments',users.Parent);assert(text.includes('Browser tuition'),text);await evaluate(`[...document.querySelectorAll('#family-test button')].find(b=>b.textContent==='Pay from PKR wallet').click()`);await new Promise(resolve=>setTimeout(resolve,1200));assert.equal((await model('Fee').findOne({title:'Browser tuition'})).status,'paid');console.log('PASS actual parent wallet tuition checkout from browser');
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 const testPassword='IsolatedFamilyTest!2026';for(const user of Object.values(users)){user.passwordHash=await model('User').hashPassword(testPassword);user.emailVerified=true;await user.save();}
 async function loginDashboard(user,role){
  await evaluate(`(async()=>{window.__familyRoot?.unmount();localStorage.removeItem('cz_access_token');localStorage.removeItem('cz_refresh_token');localStorage.removeItem('cz_user');localStorage.setItem('careerz_lang','en');window.history.replaceState({},'', '/login');const harness=await import('/audit/parent-dashboard-harness.jsx');window.__familyRoot=harness.mount(document.querySelector('#family-test'));})()`);
  for(let n=0;n<40;n++){if(await evaluate(`!!document.querySelector('#login-email')`))break;await new Promise(resolve=>setTimeout(resolve,250));}assert(await evaluate(`!!document.querySelector('#login-email')`),'Login form failed to render: '+await evaluate(`document.querySelector('#family-test').innerText`));
  await evaluate(`(()=>{const set=(selector,value)=>{const field=document.querySelector(selector);Object.getOwnPropertyDescriptor(field.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set.call(field,value);field.dispatchEvent(new Event(field.tagName==='SELECT'?'change':'input',{bubbles:true}));};set('#login-email',${JSON.stringify(user.email)});set('#login-password',${JSON.stringify(testPassword)});set('#login-as',${JSON.stringify(role)});})()`);
  await new Promise(resolve=>setTimeout(resolve,100));await evaluate(`document.querySelector('#login-email').form.requestSubmit()`);await new Promise(resolve=>setTimeout(resolve,2600));
  const rendered=await evaluate(`document.querySelector('#family-test').innerText`);assert(rendered.includes('Welcome back')||role==='student'&&rendered.includes('Student'),rendered);assert.equal(await evaluate(`window.location.pathname`),'/dashboard');assert(await evaluate(`!!document.querySelector('#family-test img')`),'Dashboard logo missing');console.log('PASS actual '+role+' password login and dashboard');
 }
 for(const [key,role] of [['Parent','parent'],['Student','student'],['Teacher','teacher'],['Owner','institution_owner']]){
  await loginDashboard(users[key],role);
  if(key==='Parent'){await evaluate(`(()=>{const b=[...document.querySelectorAll('#family-test button')].find(b=>b.textContent.trim()==='My Children');if(!b)throw Error('My Children navigation missing');b.click();})()`);await new Promise(resolve=>setTimeout(resolve,900));assert((await evaluate(`document.querySelector('#family-test').innerText`)).includes('Student Browser Test'));console.log('PASS parent dashboard navigation to actual linked child');}
  await evaluate(`(()=>{const b=[...document.querySelectorAll('#family-test button')].find(b=>/log\s*out/i.test(b.textContent));if(!b)throw Error('Logout button missing');b.click();})()`);await new Promise(resolve=>setTimeout(resolve,700));assert.equal(await evaluate(`localStorage.getItem('cz_access_token')`),null);console.log('PASS '+role+' logout clears session');
 }


 }finally{ws?.close();chrome?.kill();if(server)await new Promise(resolve=>server.close(resolve));await mongoose.disconnect();if(db)await db.stop();}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
