const {test,before,after,mock}=require('node:test'),assert=require('node:assert/strict');
const r=require('node:module').createRequire('D:/Career-Z-backend/package.json');process.env.NODE_ENV='test';const mongoose=r('mongoose'),{MongoMemoryReplSet}=r('mongodb-memory-server');
mock.method(r('./src/services/notification.service'),'notifyParentsOfStudent',async()=>{});
const names=['User','Institution','ParentChildLink','Wallet','WalletTransaction','Fee','Setting','FamilyWalletSettlement','FamilyPlatformBalance'];const m=Object.fromEntries(names.map(n=>[n,r('./src/models/'+n)]));const pay=r('./src/controllers/familyWallet.controller').pay;let db,p,s,o,i,f;
function call(amount,key){return new Promise(resolve=>{const res={status(){return this},json(v){resolve({status:200,data:v.data})}},next=e=>resolve({status:e.statusCode||500,error:e.message});Promise.resolve(pay({user:p,params:{feeId:String(f._id)},body:{amount,requestId:key}},res,next)).catch(next);});}
before(async()=>{db=await MongoMemoryReplSet.create({replSet:{count:1}});await mongoose.connect(db.getUri());await Promise.all(Object.values(m).map(v=>v.init()));const user=(name,roles)=>m.User.create({fullName:name,email:name+'@wallet.local',passwordHash:'x',roles});[p,s,o]=await Promise.all([user('parent',['parent']),user('student',['student']),user('owner',['institution_owner'])]);i=await m.Institution.create({owner:o._id,name:'School',slug:'wallet-school',type:'school',country:'PK',verificationStatus:'approved'});await m.ParentChildLink.create({parent:p._id,student:s._id,status:'approved',requestedBy:p._id});await m.Wallet.create({user:p._id,currency:'PKR',available:1000});await m.Setting.create({key:'fee_commission_percent',value:10});f=await m.Fee.create({student:s._id,institution:i._id,title:'Tuition',currency:'PKR',amount:500,recordedBy:o._id});});
after(async()=>{await mongoose.disconnect();await db.stop();});
test('wallet fee payment conserves balances, partial receipts, commission privacy and retry idempotency',async()=>{const key='one-payment-request-01';const a=await call(200,key);assert.equal(a.status,200,a.error);assert.equal(a.data.status,'partially_paid');assert.equal(a.data.outstandingAmount,300);assert.equal(a.data.platformCommission,undefined);assert.equal((await m.Wallet.findOne({user:p._id})).available,800);assert.equal((await m.Wallet.findOne({user:o._id})).available,180);assert.equal((await m.FamilyPlatformBalance.findOne()).available,20);assert.equal((await call(200,key)).status,200);assert.equal(await m.FamilyWalletSettlement.countDocuments(),1);assert.equal((await m.Wallet.findOne({user:p._id})).available,800);});
test('concurrent payments cannot overpay or make the wallet negative',async()=>{const results=await Promise.all([call(300,'concurrent-payment-01'),call(300,'concurrent-payment-02')]);assert.equal(results.filter(r=>r.status===200).length,1,JSON.stringify(results));const fee=await m.Fee.findById(f._id);assert.equal(fee.status,'paid');assert.equal(fee.paidAmount,500);assert.equal((await m.Wallet.findOne({user:p._id})).available,500);assert.equal(await m.FamilyWalletSettlement.countDocuments(),2);});
test('revoked payment permission blocks wallet debit even for a retry',async()=>{await m.ParentChildLink.updateOne({parent:p._id},{'permissions.payFees':false});assert.equal((await call(200,'one-payment-request-01')).status,403);assert.equal((await m.Wallet.findOne({user:p._id})).available,500);});
test('wallet refund returns actual payer funds and reverses institution and commission once',async()=>{await m.Fee.updateOne({_id:f._id},{refund:{status:'approved',amount:500}});const refund=r('./src/controllers/familyWallet.controller').refund;const row=await refund(f._id,o._id);assert.equal(row.status,'refunded');assert.equal((await m.Wallet.findOne({user:p._id})).available,1000);assert.equal((await m.Wallet.findOne({user:o._id})).available,0);assert.equal((await m.FamilyPlatformBalance.findOne()).available,0);await assert.rejects(()=>refund(f._id,o._id),e=>e.statusCode===409);assert.equal((await m.Wallet.findOne({user:p._id})).available,1000);});
