const {test,before,after,beforeEach,mock}=require('node:test');
const assert=require('node:assert/strict');
const r=require('node:module').createRequire('D:/Career-Z-backend/package.json');
process.env.NODE_ENV='test';process.env.DISABLE_SUBSCRIPTION_LIMITS='true';
const mongoose=r('mongoose'),{MongoMemoryServer}=r('mongodb-memory-server');
const notifications=r('./src/services/notification.service');mock.method(notifications,'notify',async()=>{});mock.method(notifications,'notifyParentsOfStudent',async()=>{});
const names=['User','Institution','StudentProfile','StudentInstitutionMembership','ParentChildLink','Course','Enrollment','Attendance','Result','Certificate','Achievement','LibraryBook','LibraryLoan','FamilyObservation','FamilyConsentRequest','ParentPermission','TimetableEntry','ClassSection','Exam','Fee','ParentTeacherMeeting','FamilyAlert','GroupConversation','GroupMessage'];
const m=Object.fromEntries(names.map(n=>[n,r('./src/models/'+n)]));
const parent=r('./src/controllers/parent.controller'),family=r('./src/controllers/family.controller'),access=r('./src/utils/messageAccess'),ptm=r('./src/controllers/ptm.controller');
function call(fn,user,params={},body={},query={}){return new Promise(resolve=>{let status=200;const res={status(n){status=n;return this},json(b){resolve({status,data:b.data});return this}};const next=e=>resolve({status:e.statusCode||500,error:e.message});Promise.resolve(fn({user,params,body,query},res,next)).catch(next);});}
let db,p,s,t,o,x,i,c;
before(async()=>{db=await MongoMemoryServer.create();await mongoose.connect(db.getUri());await Promise.all(Object.values(m).map(v=>v.init()));});
after(async()=>{await mongoose.disconnect();await db.stop();});
beforeEach(async()=>{await Promise.all(Object.values(m).map(v=>v.deleteMany({})));const user=(name,roles)=>m.User.create({fullName:name,email:name+'@test.local',passwordHash:'x',roles});[p,s,t,o,x]=await Promise.all([user('parent',['parent']),user('student',['student']),user('teacher',['teacher']),user('owner',['institution_owner']),user('outsider',['teacher'])]);i=await m.Institution.create({name:'School',slug:'school',type:'school',owner:o._id,country:'PK',verificationStatus:'approved'});await m.StudentProfile.create({user:s._id,primaryInstitution:i._id});c=await m.Course.create({title:'Math',teacher:t._id,institution:i._id,isFree:true,published:true});await m.Enrollment.create({student:s._id,course:c._id,status:'active'});});
const link=()=>m.ParentChildLink.create({parent:p._id,student:s._id,requestedBy:p._id,status:'approved',relationship:'guardian'});
test('student invitation requires parent approval, shows both parties, and revocation blocks academics',async()=>{let a=await call(parent.requestLink,s,{}, {parentEmail:p.email,relationship:'mother'});assert.equal(a.status,201,a.error);const id=String(a.data._id);assert.equal((await call(parent.respondToLink,s,{id},{decision:'approved'})).status,403);assert.equal((await call(parent.respondToLink,p,{id},{decision:'approved'})).status,200);assert.equal((await call(parent.myLinkRequests,s)).data.length,1);assert.equal((await call(family.overview,p,{studentId:String(s._id)})).status,200);assert.equal((await call(parent.unlinkChild,s,{id})).status,200);assert.equal((await call(family.overview,p,{studentId:String(s._id)})).status,403);});
test('role misuse, strict permissions and sponsors are rejected',async()=>{assert.equal((await call(parent.requestLink,s,{}, {studentEmail:p.email})).status,403);const l=await link();assert.equal((await call(parent.updateLinkPermissions,s,{id:String(l._id)},{payFees:'false'})).status,422);await m.ParentChildLink.updateOne({_id:l._id},{relationship:'sponsor'});assert.equal((await call(parent.updateLinkPermissions,s,{id:String(l._id)},{viewHealth:true})).status,422);});
test('teacher and institution messaging are bidirectional and expire on unlink or dropped enrollment',async()=>{const l=await link();assert.equal(await access.canCommunicate(p._id,t._id),true);assert.equal(await access.canCommunicate(t._id,p._id),true);assert.equal(await access.canCommunicate(p._id,o._id),true);assert.equal(await access.canCommunicate(p._id,x._id),false);await m.Enrollment.updateOne({student:s._id},{status:'dropped'});assert.equal(await access.canCommunicate(p._id,t._id),false);await m.ParentChildLink.deleteOne({_id:l._id});assert.equal(await access.canCommunicate(p._id,o._id),false);});
test('exam schedule excludes all future paper contents and dropped enrollment',async()=>{await link();await m.Exam.collection.insertOne({course:c._id,title:'Future exam',published:true,scheduledDate:new Date(Date.now()+86400000),questions:[{correctOption:1,text:'Private'}]});const a=await call(parent.childExams,p,{studentId:String(s._id)});assert.equal(a.data.length,1);assert.equal(a.data[0].questions,undefined);await m.Enrollment.updateOne({student:s._id},{status:'dropped'});assert.equal((await call(parent.childExams,p,{studentId:String(s._id)})).data.length,0);});
test('monthly overview contains only child attendance and refuses invalid months or unrelated children',async()=>{await link();await m.Attendance.create({date:new Date('2026-10-05'),markedBy:t._id,records:[{student:s._id,status:'half_day'},{student:x._id,status:'absent'}]});await m.Attendance.create({date:new Date('2026-09-05'),markedBy:t._id,records:[{student:s._id,status:'absent'}]});const a=await call(family.overview,p,{studentId:String(s._id)},{},{month:'2026-10'});assert.equal(a.status,200,a.error);assert.equal(a.data.attendance.length,1);assert.equal(a.data.attendanceTotals.half_day,1);assert.equal(a.data.attendanceTotals.absent,0);assert.equal((await call(family.overview,p,{studentId:String(x._id)})).status,403);assert.equal((await call(family.overview,p,{studentId:String(s._id)},{},{month:'2026-13'})).status,422);});
test('school request, guardian signature, withdrawal, school visibility and expiry work end to end',async()=>{await link();const params={institutionId:String(i._id)};const a=await call(family.requestConsent,o,params,{studentId:String(s._id),type:'trip',title:'Trip'});assert.equal(a.status,201,a.error);const id=String(a.data._id);assert.equal((await call(family.respondConsent,p,{id},{decision:'granted',signedName:p.fullName})).status,200);assert.equal((await call(family.institutionRequests,o,params)).data[0].responses[0].decision,'granted');assert.equal((await call(family.respondConsent,p,{id},{decision:'denied',signedName:p.fullName})).status,200);assert.equal(await m.ParentPermission.countDocuments({request:id}),1);assert.equal((await m.ParentPermission.findOne({request:id})).history.length,2);await m.FamilyConsentRequest.updateOne({_id:id},{expiresAt:new Date(0)});assert.equal((await call(family.respondConsent,p,{id},{decision:'granted',signedName:p.fullName})).status,409);assert.equal((await call(family.institutionRequests,x,params)).status,403);});
test('teacher observations reach only connected parent overview and reject outsider teachers',async()=>{await link();const params={institutionId:String(i._id)},body={studentId:String(s._id),type:'progress',text:'Practice fractions'};assert.equal((await call(family.observation,x,params,body)).status,403);assert.equal((await call(family.observation,t,params,body)).status,201);assert.equal((await call(family.overview,p,{studentId:String(s._id)})).data.behavior[0].text,body.text);});
test('independent-course teacher can receive PTM and video confirmation creates a unique HTTPS room',async()=>{await link();const a=await call(ptm.requestMeeting,p,{}, {studentId:String(s._id),teacherId:String(t._id),requestedDate:new Date(Date.now()+86400000),mode:'video'});assert.equal(a.status,201,a.error);const b=await call(ptm.respondToMeeting,t,{id:String(a.data._id)},{decision:'confirmed'});assert.equal(b.status,200,b.error);assert.match(b.data.meetingLink,/^https:\/\/meet\.jit\.si\/careerz-ptm-/);});
test('repeated absence and PTM reminders are recipient-specific and deduplicated across scheduler runs',async()=>{await link();const now=new Date();for(let n=1;n<=3;n++)await m.Attendance.create({date:new Date(now.getTime()-n*86400000),markedBy:t._id,records:[{student:s._id,status:'absent'}]});await m.ParentTeacherMeeting.create({parent:p._id,teacher:t._id,student:s._id,requestedDate:new Date(now.getTime()+3600000),confirmedDate:new Date(now.getTime()+3600000),status:'confirmed'});const job=r('./src/services/familyAutomation.service').runFamilyAutomation;assert.equal((await job(now)).sent,3);assert.equal((await job(now)).sent,0);assert.equal(await m.FamilyAlert.countDocuments({delivered:true}),3);});
test('secondary institution membership is visible and withdrawal removes institution discovery',async()=>{await link();const second=await m.Institution.create({name:'Second school',slug:'second',type:'school',owner:o._id,country:'PK'});await m.StudentInstitutionMembership.create({student:s._id,institution:second._id,status:'active'});assert.equal((await call(parent.myChildren,p)).data[0].student.institutions.length,2);await m.StudentInstitutionMembership.updateOne({student:s._id,institution:second._id},{status:'withdrawn'});assert.equal((await call(parent.myChildren,p)).data[0].student.institutions.length,1);});
test('institution guardian group stops reads and sends immediately after unlink',async()=>{const l=await link();const group=await m.GroupConversation.create({name:'Guardian group',institution:i._id,createdBy:o._id,participants:[o._id,p._id]});const ctrl=r('./src/controllers/groupConversation.controller');assert.equal((await call(ctrl.sendMessage,p,{id:String(group._id)},{text:'Hello school'})).status,201);assert.equal((await call(ctrl.listMessages,p,{id:String(group._id)})).status,200);await m.ParentChildLink.deleteOne({_id:l._id});assert.equal((await call(ctrl.listMessages,p,{id:String(group._id)})).status,403);assert.equal((await call(ctrl.sendMessage,p,{id:String(group._id)},{text:'Must not send'})).status,403);assert.equal((await call(ctrl.myGroups,p)).data.length,0);});
test('parent portfolio library loans are child-scoped and published school material rejects outsiders',async()=>{await link();const book=await m.LibraryBook.create({title:'Math book',institution:i._id,addedBy:o._id});await m.LibraryLoan.create({institution:i._id,book:book._id,issuedBy:o._id,borrower:s._id,dueDate:new Date()});await m.LibraryLoan.create({institution:i._id,book:book._id,issuedBy:o._id,borrower:x._id,dueDate:new Date()});const a=await call(family.overview,p,{studentId:String(s._id)});assert.equal(a.status,200,a.error);assert.equal(a.data.libraryLoans.length,1);assert.equal(a.data.libraryLoans[0].book.title,'Math book');const ctrl=r('./src/controllers/newsletter.controller');assert.equal((await call(ctrl.publishedForMyInstitution,p,{},{},{institution:String(i._id)})).status,200);assert.equal((await call(ctrl.publishedForMyInstitution,x,{},{},{institution:String(i._id)})).status,403);});
test('four authenticated roles complete invitation → approval → school consent → teacher update → parent view → revoke over HTTP',async()=>{
 const express=r('express'),jwt=r('jsonwebtoken'),env=r('./src/config/env');
 for(const user of [p,s,t,o]){await r('./src/models/RoleRequest').create({user:user._id,requestedRole:user.roles[0],status:'approved'});await r('./src/models/UserProfile').create({user:user._id,role:user.roles[0],completed:true,percent:100});}
 const app=express();app.use(express.json());app.use('/api/parents',r('./src/routes/parent.routes'));app.use('/api/institutions',r('./src/routes/institution.routes'));app.use('/api/messages',r('./src/routes/message.routes'));app.use((e,req,res,next)=>res.status(e.statusCode||500).json({message:e.message}));
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const base='http://127.0.0.1:'+server.address().port+'/api';
 async function api(user,path,method='GET',body){const response=await fetch(base+path,{method,headers:{Authorization:'Bearer '+jwt.sign({sub:String(user._id)},env.jwt.accessSecret,{expiresIn:'5m'}),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:response.status,...await response.json()};}
 try{
  assert.equal((await fetch(base+'/parents/children')).status,401);
  const invitation=await api(s,'/parents/link-requests','POST',{parentEmail:p.email,relationship:'guardian'});assert.equal(invitation.status,201,invitation.message);const id=invitation.data._id;
  assert.equal((await api(p,`/parents/link-requests/${id}/respond`,'PATCH',{decision:'approved'})).status,200);
  const request=await api(o,`/institutions/${i._id}/family/consent-requests`,'POST',{studentId:String(s._id),type:'trip',title:'Science trip'});assert.equal(request.status,201,request.message);
  assert.equal((await api(p,`/parents/consent-requests/${request.data._id}/respond`,'POST',{decision:'granted',signedName:p.fullName})).status,200);
  assert.equal((await api(t,`/institutions/${i._id}/family/observations`,'POST',{studentId:String(s._id),type:'progress',text:'Revise fractions'})).status,201);
  const overview=await api(p,`/parents/children/${s._id}/overview`);assert.equal(overview.status,200,overview.message);assert.equal(overview.data.behavior[0].text,'Revise fractions');assert.equal(overview.data.consentRequests[0].response.decision,'granted');
  assert.equal((await api(o,`/institutions/${i._id}/parents`)).data.length,1);
  assert.equal((await api(s,`/parents/link-requests/${id}`,'DELETE')).status,200);
  assert.equal((await api(p,`/parents/children/${s._id}/overview`)).status,403);
 }finally{await new Promise(resolve=>server.close(resolve));}
});
