const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),{spawn}=require('child_process'),assert=require('assert/strict');
(async()=>{
 const {build}=await import('vite'),react=(await import('@vitejs/plugin-react')).default;
 const temporaryRoot=fs.mkdtempSync(path.join(os.tmpdir(),'careerz-study-'));
 const output=path.join(temporaryRoot,'dist');
 await build({configFile:false,plugins:[react()],build:{outDir:output,emptyOutDir:true,rollupOptions:{input:path.resolve('test/browser-fixture/index.html')}},logLevel:'error'});
 console.log('Fixture built.');
 const server=http.createServer((req,res)=>{let target=path.resolve(output,'.'+decodeURIComponent(req.url.split('?')[0]));if(!target.startsWith(output+path.sep)||!fs.existsSync(target)||fs.statSync(target).isDirectory())target=path.join(output,'test/browser-fixture/index.html');const ext=path.extname(target);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[ext]||'application/octet-stream');fs.createReadStream(target).pipe(res);});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
 const browser=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--no-first-run','--disable-gpu','--remote-debugging-port=9238',`--user-data-dir=${path.join(temporaryRoot,'profile')}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
 let socket,id=0;const pending=new Map(),contexts=new Map(),frames=new Map();
 try {
  let targets;for(let i=0;i<40;i++){try{targets=await(await fetch('http://127.0.0.1:9238/json',{signal:AbortSignal.timeout(600)})).json();if(targets.some(t=>t.type==='page'))break;}catch{}await new Promise(r=>setTimeout(r,250));}
  if(!targets?.some(t=>t.type==='page'))throw new Error('Headless browser debugging endpoint did not start.');console.log('Browser connected.');
  socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);if(p)m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}else if(m.method==='Target.attachedToTarget'){if(m.params.targetInfo.type==='iframe')frames.set(m.params.targetInfo.targetId,m.params.sessionId);}else if(m.method==='Runtime.executionContextCreated'){const c=m.params.context;contexts.set(c.id,c);}else if(m.method==='Runtime.executionContextDestroyed')contexts.delete(m.params.executionContextId);};
  function call(method,params={},sessionId){return new Promise((resolve,reject)=>{const key=++id;const timer=setTimeout(()=>{pending.delete(key);reject(new Error('CDP timeout: '+method));},15000);pending.set(key,{resolve:r=>{clearTimeout(timer);resolve(r);},reject:e=>{clearTimeout(timer);reject(e);}});socket.send(JSON.stringify({id:key,method,params,sessionId}));});}
  async function evaluate(expression,contextId){const r=await call('Runtime.evaluate',{expression:'(async()=>{'+(expression.includes(';')?expression:'return ('+expression+');')+'})()',contextId,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text+' '+r.exceptionDetails.exception?.description);return r.result.value;}
  await call('Runtime.enable');await call('Page.enable');await call('Target.setAutoAttach',{autoAttach:true,waitForDebuggerOnStart:false,flatten:true});await call('Page.navigate',{url:origin});for(let i=0;i<50;i++){if(await evaluate('!!window.studyTest'))break;await new Promise(r=>setTimeout(r,100));}
  for(const role of ['student','teacher','institution']){await evaluate('studyTest.mountLearning('+JSON.stringify(role)+')');await new Promise(r=>setTimeout(r,250));const text=await evaluate('document.body.innerText');assert.match(text,/Curriculum/);if(role==='student')assert.doesNotMatch(text,/Add practice activity|Publishing policy/);else assert.match(text,/Add practice activity/);if(role==='institution')assert.match(text,/Publishing policy/);}
  await evaluate('studyTest.downloadCourse("course-A")');assert.equal(await evaluate('(await studyTest.offlinePackages())[0].files[location.origin+"/fixture.pdf"].size'),18);
  await evaluate('studyTest.queueCompletion({_id:"lesson-A",revision:1})');assert.equal(await evaluate('(await studyTest.pendingProgress()).length'),1);
  await evaluate('studyTest.session.set({user:{_id:"offline-user-B"}})');assert.equal(await evaluate('(await studyTest.offlinePackages()).length'),0);assert.equal(await evaluate('(await studyTest.pendingProgress()).length'),0);
  await evaluate('studyTest.session.set({user:{_id:"offline-user-A"}}); studyTest.saveDraft("study-notes","Draft survives reload")');
  await evaluate('studyTest.syncProgress()');assert.equal(await evaluate('(await studyTest.pendingProgress()).length'),0);
  await evaluate('studyTest.mount()');await new Promise(r=>setTimeout(r,200));assert.match(await evaluate('document.body.innerText'),/Saved lesson/);
  await evaluate('navigator.serviceWorker.ready');for(let i=0;i<30;i++){if(await evaluate('caches.open("careerz-shell-learning-v1").then(async c=>(await c.keys()).some(r=>r.url.includes("/assets/")))'))break;await new Promise(r=>setTimeout(r,100));}
  await call('Network.enable');await call('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await call('Page.reload');for(let i=0;i<50;i++){try{if(await evaluate('!!window.studyTest'))break;}catch{}await new Promise(r=>setTimeout(r,100));}
  assert.equal(await evaluate('await studyTest.loadDraft("study-notes")'),'Draft survives reload');assert.equal(await evaluate('(await studyTest.offlinePackages()).length'),1);
  await evaluate('studyTest.mount()');await new Promise(r=>setTimeout(r,150));assert.match(await evaluate('document.body.innerText'),/Offline notes|Saved lesson/);
  await call('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
  await evaluate(`const frame=document.createElement('iframe');frame.sandbox='allow-scripts';frame.srcdoc=studyTest.codingDocument('console.log("WORKER_OK")');document.body.append(frame);`);await new Promise(r=>setTimeout(r,800));
  let result;if(frames.size){const targetSession=Array.from(frames.values()).at(-1);result=(await call('Runtime.evaluate',{expression:'document.body.innerText',returnByValue:true},targetSession)).result.value;}else {const tree=await call('Page.getFrameTree');const frame=tree.frameTree.childFrames.at(-1).frame;const world=await call('Page.createIsolatedWorld',{frameId:frame.id,worldName:'study-verification'});result=await evaluate('document.body.innerText',world.executionContextId);}assert.match(result,/WORKER_OK/);
  await evaluate('const frame=document.createElement("iframe");frame.sandbox="allow-scripts";frame.srcdoc=studyTest.codingDocument("while(true){}");document.body.append(frame);');let loopResult='';for(let attempt=0;attempt<40;attempt++){await new Promise(r=>setTimeout(r,250));const loopSession=Array.from(frames.values()).at(-1);loopResult=(await call('Runtime.evaluate',{expression:'document.body.innerText',returnByValue:true},loopSession)).result.value;if(loopResult.includes('execution limit'))break;}assert.match(loopResult,/two-second execution limit/);
  await evaluate('studyTest.session.clear()');await new Promise(r=>setTimeout(r,250));await evaluate('studyTest.session.set({user:{_id:"offline-user-A"},accessToken:"fixture-only"})');assert.equal(await evaluate('(await studyTest.offlinePackages()).length'),0);
  console.log('PASS: real-browser IndexedDB files, account isolation, progress sync, offline reload, retained drafts, role-specific learning UI, safe coding worker with timeout and logout purge.');
 } finally {if(socket?.readyState===1)socket.send(JSON.stringify({id:++id,method:'Browser.close'}));await new Promise(r=>setTimeout(r,300));socket?.close();browser.kill();server.close();const resolved=path.resolve(temporaryRoot);if(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('careerz-study-'))try{fs.rmSync(resolved,{recursive:true,force:true,maxRetries:5,retryDelay:100});}catch{ /* Browser may still release its temporary profile. */ }}
})().catch(error=>{console.error(error);process.exitCode=1;});
