import PublicDirectory from '../components/PublicDirectory';
import SafePageContent from '../components/SafePageContent';
import { useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import AuthNavbar from '../components/AuthNavbar';
import SiteFooter from '../components/SiteFooter';
import PageSeo from '../components/PageSeo';
import { PUBLIC_PAGES } from '../content/publicPages';
import { apiRequest } from '../api/client';
export default function PublicPage(){const params=useParams();const postSlug=params.postSlug;const slug=params.slug || (postSlug ? 'blog' : '');const fallback=PUBLIC_PAGES.find(p=>p.slug===slug);const [page,setPage]=useState(null),[posts,setPosts]=useState([]),[error,setError]=useState('');useEffect(()=>{let alive=true;setPage(null);setError('');apiRequest(postSlug?'/blog/'+postSlug:'/pages/'+slug,{auth:false}).then(p=>{if(alive)setPage(p);}).catch(e=>{if(alive&&!fallback)setError(e.message);});if(slug==='blog'&&!postSlug)apiRequest('/blog',{auth:false}).then(p=>{if(alive)setPosts(p);}).catch(()=>{});return()=>{alive=false;};},[slug,postSlug]);const p=page||fallback;return <><PageSeo title={p?.seoTitle||p?.title||'Page unavailable'} description={p?.seoDescription||p?.description||p?.excerpt||'CareerZ public information'} path={'/'+slug+(postSlug?'/'+postSlug:'')} noindex={!p}/><AuthNavbar/><main className="public-page"><header className="public-page-hero"><nav className="public-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><span>{p?.title||'Page unavailable'}</span></nav><h1>{p?.title||'Page unavailable'}</h1><p>{p?.description||p?.seoDescription||p?.excerpt}</p></header><div className="public-page-layout"><article className="public-content-card">{error&&<p className="public-error">{error}</p>}{page ? <SafePageContent content={p?.content || ''}/> : <div className="public-page-content">{String(p?.content||'').split('\n\n').map((block,index)=>{const lines=block.split('\n');return <section key={index}>{index>0&&lines.length>1&&<h2>{lines.shift()}</h2>}<p>{lines.join(' ')}</p></section>;})}</div>}{slug==='contact'&&<div className="public-contact-cards"><a href="mailto:info@careerz.pk">Email: info@careerz.pk</a><a href="tel:+923002425623">Call: 0300-2425623</a></div>}{slug==='blog'&&!postSlug&&<div className="public-page-links">{posts.map(post=><Link key={post._id} to={'/blog/'+post.slug} className="discovery-card"><h2>{post.title}</h2><p>{post.excerpt}</p></Link>)}</div>}{slug==='sitemap'&&<nav className="public-page-links" aria-label="All public pages">{PUBLIC_PAGES.map(p=><Link key={p.slug} to={'/'+p.slug}>{p.title}</Link>)}<Link to="/login">Sign in</Link><Link to="/signup">Create account</Link></nav>}{['institutions','courses','jobs','scholarships'].includes(slug)&&<PublicDirectory kind={slug}/>}
{['institutions','courses','jobs','scholarships','marketplace','agent-program','donor-program','become-a-seller'].includes(slug)&&<p><Link className="btn btn-primary" to="/signup">Get started</Link> <Link to="/dashboard">Open dashboard</Link></p>}</article><aside className="public-related"><h2>Explore CareerZ</h2>{[['About Us','about'],['Courses','courses'],['Institutions','institutions'],['FAQ','faq'],['Help Center','help'],['Contact','contact']].filter(([,link])=>link!==slug).map(([label,link])=><Link key={link} to={'/'+link}>{label}</Link>)}<p>Learn, connect and find opportunities with your education community.</p><Link to="/signup">Create your account</Link></aside></div></main><SiteFooter/></>;}
