export const PUBLIC_PAGES = [
['about','About Us','CareerZ connects education with opportunity.','Students, teachers, institutions, parents, employers, agents and donors share one platform for learning, institution operations and career development.'],
['contact','Contact Us','Talk to the CareerZ team.','For platform enquiries, email info@careerz.pk or call 0300-2425623. Address: Saram Abad Basti, Saram Abad, P/O Basti Khair Pur Sadat, Tehsil Ali Pur, District Muzaffargarh, Punjab, Pakistan.'],
['faq','FAQ','Answers to common questions.','How do I join? Create an account, complete verification and your profile. How do I find my courses? Open My Courses in your dashboard. Who manages institute access? Your institution approves membership and assigns classes.'],
['help','Help Center','Find support for your account and learning.','Use your dashboard help desk for institution issues. Contact info@careerz.pk for platform access problems. Include the affected page and error message; never send passwords or API keys.'],
['privacy','Privacy Policy','How your information is used.','CareerZ processes account, profile, enrollment and activity information to provide its services. Institution records are available to authorized users according to their roles. Contact info@careerz.pk for privacy and account-data requests.'],
['terms','Terms & Conditions','Using CareerZ responsibly.','Provide accurate account details, respect other users and upload only content you have permission to share. Keep your credentials private. Institution and paid-service conditions are shown in their applicable enrollment or checkout flows.'],
['cookies','Cookie Policy','Browser storage and your choices.','Authentication and preferences use browser storage. Offline Study stores downloaded learning resources on your device. Clear site data to remove local copies; doing so can remove unsynced work.'],
['refund','Refund Policy','Get help with a payment or refund.','Contact support with your transaction reference and the purchased service. Refund eligibility depends on the applicable purchase terms and payment provider. Do not include card details in your message.'],
['cancellation','Cancellation Policy','Manage cancellations and access.','Check the applicable course or subscription terms before cancelling. Contact your institution for enrollment changes and platform support for payment-related cancellation requests.'],
['community-guidelines','Community Guidelines','Keep the community useful and respectful.','Discuss constructively, respect privacy, avoid harassment and spam, and report inappropriate content through the help desk. Teachers and authorized moderators manage course discussions.'],
['code-of-conduct','Code of Conduct','Academic and professional standards.','Submit your own work, acknowledge sources and AI assistance, respect assessment rules and do not impersonate another user. Follow your institution\u0027s academic policies.'],
['careers','Careers','Build the future of education with us.','For opportunities with CareerZ, contact info@careerz.pk. For employer job listings, explore Jobs.'],
['blog','Blog','Ideas and updates from CareerZ.','Published articles appear here as the editorial team releases them.'],
['news','News','Platform announcements.','Visit this page for published CareerZ announcements and news.'],
['partnership','Partnership','Work with CareerZ.','Institutions, employers and education partners can contact info@careerz.pk to discuss collaboration.'],
['advertise','Advertise With Us','Reach the education community.','Contact info@careerz.pk with your organization, campaign goals and intended audience.'],
['press','Press & Media','Media enquiries and brand information.','For interviews, platform information or permission to use brand materials, contact info@careerz.pk.'],
['accessibility','Accessibility','Education that more people can access.','Learning resources include text sizing, contrast controls and read-aloud tools. Video captions depend on available subtitle tracks. Contact support to report an accessibility barrier.'],
['sitemap','Sitemap','Explore CareerZ pages.','Browse public information, platform discovery pages and account entry points.'],
['institutions','Institutions','Find your education community.','Explore institutions and manage approved memberships in your dashboard.'],['courses','Courses','Learn with your teachers and institutions.','Discover learning opportunities and access your enrolled courses in My Courses.'],['jobs','Jobs','Connect learning to a career.','Explore employer opportunities and your institution\u0027s Placement Office.'],['scholarships','Scholarships','Support your learning journey.','Explore scholarship opportunities and follow each provider\u0027s eligibility and application instructions.'],['marketplace','Marketplace','Education resources and services.','Access marketplace opportunities through your CareerZ account.'],['agent-program','Agent Program','Connect institutions and learners.','Create an agent account to explore your available programs.'],['donor-program','Donor Program','Support education.','Create a donor account to explore supported education initiatives.'],['become-a-seller','Become a Seller','Share education products and services.','Create your account to explore marketplace participation.']
].map(([slug,title,description,content])=>({slug,title,description,content}));

const DETAILS = {
  about: '\n\nLearning and teaching\nStudents can follow enrolled courses, read lessons, submit assignments, take assessments and join live classes. Teachers organize lessons and resources, manage discussions and review student work.\n\nInstitution operations\nInstitutions manage memberships, staff permissions, classes, timetables and attendance. Access to private records follows the assigned role and institution membership.\n\nEducation to opportunity\nCareerZ brings course discovery, scholarships, employer opportunities and education resources into the same account experience. Explore the platform links below or contact our team for a partnership.',
  faq: '\n\nCan I use more than one role?\nYour available workspaces depend on your account and approved memberships. Switch workspaces from the dashboard when a role is available.\n\nWhere are live classes?\nStudents open My Classes; teachers schedule and manage sessions from Live Classes. Camera, microphone and recording depend on browser permission and institution settings.\n\nHow do recordings reach students?\nA local screen recording is saved to the teacher device. The teacher must publish or attach that file as an accessible lesson resource before students can watch it.\n\nCan I study offline?\nDownload eligible course resources from Offline Study while connected. Synchronize pending progress when internet access returns.\n\nWhat does AI-assisted mean?\nIt identifies content prepared with AI assistance. It does not generate a new answer when selected. Teachers review and publish lesson content.\n\nHow do I report a problem?\nUse Help Center or email info@careerz.pk with the affected page, time and error message.',
  help: '\n\nAccount access\nUse Forgot Password on the sign-in page. Check your email inbox and spam folder for verification messages. Do not share one-time codes.\n\nCourse or institution access\nConfirm that your institution membership and enrollment are approved. Ask the institution administrator to check your class assignment and role permissions.\n\nMedia and live classes\nAllow the required browser camera and microphone permissions. For a recording, select the intended browser tab and enable tab audio. Recording policies are controlled by the institution.\n\nPayments\nKeep the transaction reference and contact support if a payment status does not update. Never send card numbers, security codes or passwords.\n\nContact support\nEmail info@careerz.pk or call 0300-2425623. Include a clear description and a screenshot with private information removed.',
  privacy: '\n\nInformation used by the service\nAccount details, institution memberships, learning progress, submitted work and transaction references support account access and platform operations. Class participation and exam integrity events may be recorded in the relevant session or assessment.\n\nAccess and sharing\nTeachers and institution administrators access records needed for their assigned responsibilities. Other students do not receive administrative access to your account. Payment, email and media providers may process information needed to deliver their services.\n\nYour choices\nReview your profile and notification settings. Recording follows institution policy and applicable consent settings. Contact support for requests concerning your account information.\n\nLocal device data\nOffline resources and unsynced progress remain on your device until synchronized or removed. Sign out on shared devices and remove downloaded copies when appropriate.',
  terms: '\n\nAccounts and access\nKeep account details accurate and protect your sign-in credentials. Institution membership, enrollment and staff permissions determine available features.\n\nContent and conduct\nOnly upload materials you are entitled to use. Respect intellectual property, privacy and academic integrity. Identify AI assistance where required and follow your institution assessment rules.\n\nPaid services\nReview the displayed price, service description and applicable cancellation or refund terms before confirming a purchase. Keep your transaction reference for support.\n\nSupport and updates\nContact info@careerz.pk for platform issues. Service features and published policies may be updated; check the relevant page before using a paid service.',
  cookies: '\n\nEssential storage\nBrowser storage supports account sessions, interface preferences and offline learning. Removing essential storage can sign you out and reset preferences.\n\nOffline downloads\nDownloaded resources and unsynced learning work use device storage. Synchronize pending work before clearing site data.\n\nBrowser controls\nUse your browser settings to inspect or remove site storage and manage notification permissions. Contact support if you need help with local data.',
  refund: '\n\nBefore buying\nRead the specific service or enrollment terms shown before purchase. A course provider or payment processor may have its own refund conditions.\n\nRequest a review\nEmail info@careerz.pk with the transaction reference, service name, purchase date and reason for the request. Avoid including sensitive payment credentials.\n\nReview and status\nSupport checks the purchase and applicable terms before confirming eligibility. Processing and settlement depend on the relevant payment provider. A support request alone does not confirm a refund.',
  cancellation: '\n\nEnrollment changes\nContact your institution for course withdrawal, class changes or membership cancellation. Ask how the change affects learning access and pending assessments.\n\nPaid services\nReview the purchase conditions and contact support with your transaction reference. Cancellation and refund eligibility are separate decisions under the applicable terms.\n\nAccount requests\nFor account closure or information requests, contact info@careerz.pk. Save work you need and synchronize offline progress before requesting closure.',
  accessibility: '\n\nReading tools\nLesson views provide text sizing, contrast controls and read-aloud tools where supported by the browser.\n\nAudio and video\nCaptions and translated subtitle tracks depend on the tracks supplied with the media. Teachers can attach supported subtitle resources; an AI-assisted label alone does not create subtitles.\n\nReport a barrier\nEmail info@careerz.pk with the page, device, browser and a description of the problem. Mention any assistive technology you are using so the issue can be reproduced.',
  partnership: '\n\nEducation institutions\nTell us about your institution, location, learner groups and the teaching or administration workflows you want to support.\n\nEmployers and donors\nDescribe your placement opportunities or education-support initiative and who it serves.\n\nStart a conversation\nEmail info@careerz.pk with your organization name, contact person and proposed collaboration.',
  'community-guidelines': '\n\nUseful discussions\nKeep questions relevant to the course, write clear replies and acknowledge sources. Respect different backgrounds and opinions.\n\nProtect people\nDo not publish another person private information, post harassment or share misleading links.\n\nModeration\nTeachers and authorized moderators may pin, lock or hide discussions. Report concerns through your help desk or platform support.',
  'code-of-conduct': '\n\nAcademic integrity\nFollow exam instructions, submit original work and disclose assistance when required. Monitoring flags are evidence for review by the teacher.\n\nProfessional behavior\nCommunicate respectfully, protect confidential records and use only the permissions assigned to your role.\n\nReporting\nContact your institution for academic concerns and platform support for access or misuse concerns.',
  careers: '\n\nWorking with CareerZ\nSend your area of expertise, relevant experience and contact details to info@careerz.pk. Published openings and requirements take precedence over a general enquiry.\n\nLooking for employer opportunities?\nOpen Jobs to browse currently published listings and create an account to apply through the platform.',
  advertise: '\n\nCampaign enquiries\nShare your organization, proposed material, audience, campaign dates and preferred contact details with info@careerz.pk.\n\nContent standards\nAdvertising must respect privacy and community standards. Availability and commercial terms are confirmed separately before a campaign begins.',
  press: '\n\nMedia contact\nEmail info@careerz.pk with your publication, topic, deadline and interview request.\n\nBrand use\nRequest permission and the appropriate brand assets before publishing CareerZ logos or representing a partnership.'
};
PUBLIC_PAGES.forEach(page => { page.content += DETAILS[page.slug] || ''; });

const MORE_DETAILS = {
  about: [['A connected learning journey','Begin with an account and an approved institution membership, then follow lessons, class activities and assessments from your workspace. Learning records help students and teachers review progress together.'],['Designed around responsibilities','Students focus on learning, teachers on instruction and review, and institutions on organization and permissions. Employers, agents and donors use their relevant workspaces to connect learning with opportunities.']],
  contact: [['Choose the right contact','Ask your institution about enrollment, class placement, attendance and academic decisions. Contact CareerZ for platform access, technical issues, partnerships and payment support.'],['What to include in your message','Share your name, account email, institution if relevant, the affected page and a clear description. For a technical issue, include your device, browser, approximate time and error message.'],['Keep sensitive information private','Never send passwords, one-time codes, API keys or full card details. Remove private student records from screenshots before sharing them with support.']],
  faq: [['Why is a course or resource missing?','Your class assignment, enrollment approval or content publication status may affect visibility. Check your workspace and ask your institution or teacher to confirm access.'],['Why can I not record a class?','Recording is governed by institution settings and browser permissions. A teacher must be authorized to record before selecting a screen or tab.']],
  help: [['Describe a reproducible issue','Explain what you clicked, what you expected and what happened. Mention whether the issue also occurs after refreshing or on another supported browser.'],['Before clearing browser data','Save your work and synchronize pending offline progress. Clearing site data may remove downloaded resources and drafts that have not reached the server.']],
  privacy: [['Shared devices','Sign out when using a shared computer. Consider whether downloaded files, browser history and local offline resources can be accessed by the next person using that device.'],['Questions about your records','Identify the account and the type of information concerned when contacting support. Academic records managed by an institution may also require coordination with its administrator.']],
  terms: [['Understanding responsibilities','Teachers and institutions decide academic requirements and publication permissions. Users remain responsible for checking the instructions attached to a course, assessment, opportunity or purchase.'],['Reporting account misuse','Contact support if you suspect unauthorized access. Describe the issue without publishing another user private information or sharing your credentials.']],
  cookies: [['Permissions are separate from storage','Camera, microphone, screen capture and notifications are managed through browser permissions. Removing cookies alone may not reset these permissions; review the site permissions in your browser settings.'],['Using a shared browser','Review downloaded files as well as stored site data before leaving a shared device. Keep a copy of any work you need before deleting local resources.']],
  refund: [['Useful supporting information','Include the purchase reference, the account used and what was delivered or went wrong. Screenshots of an error or transaction status can help support investigate.'],['Follow up on the same request','Keep the support conversation and transaction reference together. If your provider supplies a settlement or refund reference, retain it for checking the payment status.']],
  cancellation: [['Plan for changes to access','Ask the service provider how cancellation affects remaining lessons, submissions, downloads and certificates. Save documents you are entitled to keep before access changes.'],['Provide a clear request','Identify the relevant account, institution, enrollment or purchased service and explain the change you want. Keep the confirmation of any approved change.']],
  'community-guidelines': [['Write a useful question','Use a specific title, describe what you tried and include enough context for someone to help. Avoid repeatedly posting the same question across discussions.'],['Respond constructively','Explain your reasoning, acknowledge helpful replies and correct mistakes respectfully. Keep private account and payment issues out of public discussions.']],
  'code-of-conduct': [['Responsible use of AI','Check AI-assisted material for accuracy and relevance before submitting or publishing it. Follow the disclosure requirements set by your teacher or institution.'],['Review concerns fairly','A monitoring event or report needs context. Explain relevant circumstances to the teacher or institution responsible for reviewing the matter.']],
  careers: [['Prepare an introduction','Tell us the role or area you are interested in, your relevant skills and a short example of your work. Include a portfolio link where appropriate and avoid sending confidential material.'],['Distinguish platform roles from employment','Creating a teacher, agent or seller account provides platform access according to its requirements. It does not itself create an employment relationship with CareerZ.']],
  blog: [['What you can find here','Published articles may cover teaching practices, learning resources, institution workflows and platform updates. Open an article to read its full content.'],['Use articles alongside official instructions','An article provides context and guidance. For an enrollment, assessment, payment or application, check the current instructions in the relevant service or institution workspace.']],
  news: [['Follow relevant announcements','Look for changes affecting your workspace, learning activities or platform services. Your dashboard notifications carry account and institution-specific updates.'],['Check the context','Read an announcement in full and consider its date and intended audience. Contact your institution for clarification about an academic change.']],
  partnership: [['Prepare your proposal','Describe the learners or organizations you serve, the problem you want to solve and the proposed responsibilities of each party. Include your location and a contact person.'],['Agree the scope first','Discuss access, content ownership, delivery responsibilities and the information needed for the collaboration before sharing private records or making commitments.']],
  advertise: [['Help us understand your campaign','Include a short campaign brief, examples of proposed content and the action you want your audience to take. Mention any landing pages or resources the campaign would link to.'],['Keep messages accurate','Use clear claims and appropriate permissions for images, logos and testimonials. A campaign enquiry does not confirm placement, pricing or publication.']],
  press: [['Request accurate information','Specify which product, feature or announcement your enquiry concerns. Share the questions you want answered and your publication deadline.'],['Use the complete brand','Keep the emblem, CareerZ wordmark and tagline visible when using an approved logo. Maintain readable contrast and avoid stretching or cropping the supplied asset.']],
  accessibility: [['Make resources easier to follow','Use meaningful headings, readable text and descriptive resource names. Teachers should provide captions or written alternatives when these resources are available.'],['Language and readability','Use the header language selector for available translation options. Translation depends on service availability; review translated academic material with your teacher when meaning is unclear.']],
  sitemap: [['Navigate by purpose','Use Institutions and Courses for education discovery, Jobs and Scholarships for opportunities, and Help or FAQ for guidance. Company and policy pages explain the platform and its use.'],['Public pages and private workspaces','This directory lists public destinations. Personal learning records, institution administration and account settings are available after signing in with the appropriate permissions.']],
  institutions: [['Find your institution','Search published listings by name or location. Check that the institution matches the organization you intend to join before requesting membership.'],['After you join','Complete your profile and follow the institution approval process. Your assigned classes and permissions determine which lessons, schedules and records appear in the dashboard.']],
  courses: [['Choose a relevant course','Search by course name, subject or institution. Review the course context and confirm enrollment requirements with the teacher or provider.'],['Learning after enrollment','Open My Courses for enrolled material. Follow the lesson sequence, review attached resources and complete the assignments and assessments required by your teacher.']],
  jobs: [['Review an opportunity','Check the published role, location and requirements. Compare the opportunity with your skills and prepare an accurate profile before applying.'],['Prepare your application','Keep your experience and qualifications current. Follow the employer instructions and avoid sharing unrelated sensitive information in application material.']],
  scholarships: [['Check eligibility first','Review the provider requirements, intended study level, location and any published application dates. A listing does not guarantee selection or funding.'],['Organize your application','Prepare the requested academic information and supporting documents. Follow the provider instructions and keep a record of your submission and any follow-up requests.']],
  marketplace: [['Explore education resources','Use your CareerZ account to view the marketplace features available to your role. Review the item or service description and the seller information before proceeding.'],['Before a purchase','Check the price, delivery method, intended use and applicable service conditions. Keep the transaction reference if you need help with delivery or a payment status.']],
  'agent-program': [['Prepare your agent profile','Complete your account information and describe the institutions or learners you work with. Follow the verification and program requirements shown in your workspace.'],['Represent information accurately','Share accurate program details and explain the relevant enrollment steps. Check current program conditions before promising fees, admissions or other outcomes.']],
  'donor-program': [['Define your education support','Describe the learners or initiative you want to support and the intended purpose. Use the donor workspace to explore the features available to your account.'],['Follow the initiative requirements','Review the published eligibility, application and reporting instructions for the relevant initiative. Keep records of your support and any communication with the provider.']],
  'become-a-seller': [['Prepare your seller account','Complete your profile and provide the information required for marketplace participation. Describe your products or services clearly and use material you are entitled to publish.'],['Make listings useful','Explain what the buyer receives, the intended audience and the delivery method. Keep pricing and service conditions accurate and provide clear support information.']]
};
PUBLIC_PAGES.forEach(page => {
  page.content += (MORE_DETAILS[page.slug] || []).map(([heading,body]) => '\n\n'+heading+'\n'+body).join('');
});
