import { useEffect, useRef, useState } from 'react';
import { apiRequest } from '../api/client';
import { isPlatformUploadAvailable, uploadToPlatformStorage } from '../utils/platformUpload';
export default function LiveLearningTools({ session, role, localStream, onGroupChange, onPolicyChange, onError }) {
  const teacher = role === 'teacher';
  const [data, setData] = useState({ board: [], groups: [], files: [], quiz: null }), [tool, setTool] = useState('stroke'), [color, setColor] = useState('#123c2f'), [text, setText] = useState(''), [points, setPoints] = useState([]), [roster, setRoster] = useState([]), [attendance, setAttendance] = useState({});
  const [groupCount, setGroupCount] = useState(2), [visit, setVisit] = useState('main'), [question, setQuestion] = useState(''), [options, setOptions] = useState('Yes\nNo'), [answer, setAnswer] = useState(0), [file, setFile] = useState({ name: '', url: '' }), [recording, setRecording] = useState(false), [blob, setBlob] = useState(null), [busy, setBusy] = useState(false);
  const svg = useRef(null), recorder = useRef(null), recordingTracks = useRef([]), lastGroup = useRef(''), draft = useRef([]);
  const recordingAudio = useRef(null);
  async function update(body) { try { setData(await apiRequest(`/live-classes/${session._id}/tools`, { method: 'POST', body })); } catch (e) { onError?.(e); } }
  useEffect(() => { let alive = true; let pending = false; async function refresh() { if (pending) return; pending = true; try { const d = await apiRequest(`/live-classes/${session._id}/tools`); if (alive) setData(d); } catch (e) { if (alive) onError?.(e); } finally { pending = false; } } refresh(); const timer = setInterval(refresh, 2500); if (teacher) apiRequest(`/live-classes/${session._id}/roster`).then(r => { if (alive) { setRoster(r.students); setAttendance(Object.fromEntries(r.records.map(r => [r.student, r.status]))); } }).catch(onError); return () => { alive = false; clearInterval(timer); recorder.current?.state === 'recording' && recorder.current.stop(); recordingTracks.current.forEach(t => t.stop()); }; }, [session._id]);
  useEffect(() => { if (teacher) return; const own = JSON.parse(localStorage.getItem('cz_user') || 'null'); const group = data.groups.find(g => g.students.includes(own?._id))?.name || 'main'; if (lastGroup.current && group !== lastGroup.current) onGroupChange?.(group); lastGroup.current = group; }, [data.groups, teacher]);
  useEffect(() => { if (data.policy) onPolicyChange?.(data.policy); }, [data.policy]);
  useEffect(() => { if (teacher && visit !== 'main' && !data.groups.some(g => g.name === visit)) { setVisit('main'); onGroupChange?.('main'); } }, [data.groups]);
  function coordinate(e) { const rect = svg.current.getBoundingClientRect(); return [Math.max(0, Math.min(1000, (e.clientX - rect.left) / rect.width * 1000)), Math.max(0, Math.min(600, (e.clientY - rect.top) / rect.height * 600))]; }
  function down(e) { svg.current.setPointerCapture(e.pointerId); const p = coordinate(e); draft.current = [p]; setPoints([p]); }
  function move(e) { if (!draft.current.length || tool !== 'stroke') return; if (draft.current.length < 250) { draft.current.push(coordinate(e)); setPoints([...draft.current]); } }
  function up(e) { if (!draft.current.length) return; const p = draft.current[0], q = coordinate(e); const operation = { type: tool, color, x: p[0], y: p[1], x2: q[0], y2: q[1], points: draft.current, text }; draft.current = []; setPoints([]); update({ action: 'board', operation }); }
  async function startRecording() { try { if (!window.MediaRecorder) throw new Error('This browser does not support recording.'); const stream = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: true }); recordingTracks.current = stream.getTracks(); let capture = stream;if(localStream?.getAudioTracks().length){const context=new AudioContext();recordingAudio.current=context;const output=context.createMediaStreamDestination();if(stream.getAudioTracks().length)context.createMediaStreamSource(new MediaStream(stream.getAudioTracks())).connect(output);context.createMediaStreamSource(new MediaStream(localStream.getAudioTracks())).connect(output);capture=new MediaStream([...stream.getVideoTracks(),...output.stream.getAudioTracks()]);}const chunks = []; const r = new MediaRecorder(capture); recorder.current = r; r.ondataavailable = e => { if (e.data.size) chunks.push(e.data); }; r.onstop = () => { const saved=new Blob(chunks,{type:r.mimeType||'video/webm'});setBlob(saved);const link=URL.createObjectURL(saved);const anchor=document.createElement('a');anchor.href=link;anchor.download=session.title+'.webm';anchor.click();setTimeout(()=>URL.revokeObjectURL(link),1000);recordingAudio.current?.close(); recordingTracks.current.forEach(t => t.stop()); setRecording(false); update({ action: 'recording', enabled: false }); }; stream.getVideoTracks()[0].onended = () => { if (r.state === 'recording') r.stop(); }; r.start(1000); setRecording(true); await update({ action: 'recording', enabled: true }); } catch (e) { onError?.(e); } }
  function downloadRecording() { const u = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = u; a.download = `${session.title}.webm`; a.click(); URL.revokeObjectURL(u); }
  async function shareRecording() { setBusy(true); try { if (!await isPlatformUploadAvailable()) throw new Error('Configure platform video storage to share recordings. You can download the recording locally now.'); const url = await uploadToPlatformStorage(new File([blob], `${session._id}.webm`, { type: blob.type }), 'class-recordings'); await apiRequest(`/live-classes/${session._id}/recording`, { method: 'POST', body: { url } }); } catch (e) { onError?.(e); } finally { setBusy(false); } }
  return <section className="dash-card" style={{ padding: 16 }}><h3>Classroom tools</h3>{data.recording && <p role="status">Teacher is recording the selected screen/tab. Participants should be aware before sharing.</p>}
    {teacher && ['physical', 'hybrid'].includes(session.mode) && <details open><summary>Physical attendance</summary>{roster.map(s => <label key={s._id} style={{ display: 'block' }}>{s.fullName}<select className="form-select" value={attendance[s._id] || 'absent'} onChange={e => setAttendance({ ...attendance, [s._id]: e.target.value })}>{['present', 'late', 'absent', 'excused'].map(v => <option key={v}>{v}</option>)}</select></label>)}<button className="btn" onClick={async () => { try { await apiRequest(`/live-classes/${session._id}/physical-attendance`, { method: 'PATCH', body: { records: roster.map(s => ({ student: s._id, status: attendance[s._id] || 'absent' })) } }); } catch (e) { onError?.(e); } }}>Save physical attendance</button><p>End Class merges on-campus and remote attendance into one record per student.</p></details>}
    {teacher && <details><summary>Classroom permissions</summary>{[['chatAllowed', 'Student chat'], ['microphoneAllowed', 'Student microphone'], ['cameraRequired', 'Student camera required'], ['screenShareAllowed', 'Student screen sharing'], ['fileSharingAllowed', 'Student file sharing']].map(([field, label]) => <label key={field} style={{ display: 'block' }}><input type="checkbox" checked={!!data.policy?.[field]} onChange={e => update({ action: 'policy', policy: { [field]: e.target.checked } })} />{label}</label>)}</details>}
    <h4>Shared whiteboard</h4><select className="form-select" value={tool} onChange={e => setTool(e.target.value)}>{['stroke', 'rect', 'circle', 'text'].map(t => <option key={t}>{t}</option>)}</select><input type="color" value={color} onChange={e => setColor(e.target.value)} /><input className="form-input" placeholder="Text, equation, chemical formula or diagram label" value={text} onChange={e => setText(e.target.value)} />
    <svg ref={svg} viewBox="0 0 1000 600" style={{ width: '100%', background: '#fff', border: '1px solid #ccc', touchAction: 'none' }} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={() => { draft.current = []; setPoints([]); }} aria-label="Collaborative whiteboard">
      {data.board.map((o, n) => o.type === 'stroke' ? <polyline key={n} points={o.points?.map(p => p.join(',')).join(' ')} stroke={o.color} strokeWidth="3" fill="none" /> : o.type === 'rect' ? <rect key={n} x={Math.min(o.x, o.x2)} y={Math.min(o.y, o.y2)} width={Math.abs(o.x2 - o.x)} height={Math.abs(o.y2 - o.y)} fill="none" stroke={o.color} strokeWidth="3" /> : o.type === 'circle' ? <ellipse key={n} cx={(o.x + o.x2) / 2} cy={(o.y + o.y2) / 2} rx={Math.abs(o.x2 - o.x) / 2} ry={Math.abs(o.y2 - o.y) / 2} fill="none" stroke={o.color} strokeWidth="3" /> : <text key={n} x={o.x} y={o.y} fill={o.color} fontSize="22">{o.text}</text>)}<polyline points={points.map(p => p.join(',')).join(' ')} stroke={color} fill="none" />
    </svg>{teacher && <><button className="btn" onClick={() => update({ action: 'clear' })}>Clear board</button><button className="btn" onClick={async () => { try { const r = await apiRequest('/ai/generate', { method: 'POST', body: { feature: 'teacher_notes', prompt: `Write a short whiteboard explanation (under 500 characters): ${text}` } }); await update({ action: 'board', operation: { type: 'text', x: 30, y: 40, text: r.result.slice(0, 1000), color } }); } catch (e) { onError?.(e); } }}>AI explanation on board</button></>}
    <h4>Breakout rooms</h4>{teacher && <><input type="number" min="2" max="10" value={groupCount} onChange={e => setGroupCount(Number(e.target.value))} /><button className="btn" onClick={() => { const count = Math.min(10, Math.max(2, groupCount)); const groups = Array.from({ length: count }, (_, n) => ({ name: `Group ${n + 1}`, students: roster.filter((_, i) => i % count === n).map(s => s._id) })); update({ action: 'groups', groups }); }}>Open groups</button><button className="btn" onClick={() => update({ action: 'groups', groups: [] })}>Return everyone to main room</button><select className="form-select" value={visit} onChange={e => { setVisit(e.target.value); onGroupChange?.(e.target.value); }}><option value="main">Main room</option>{data.groups.map(g => <option key={g.name}>{g.name}</option>)}</select></>}{data.groups.map(g => <p key={g.name}>{g.name} · {g.students.length} students</p>)}
    <h4>In-class quiz</h4>{teacher && <form onSubmit={e => { e.preventDefault(); update({ action: 'quiz', question, options: options.split('\n').filter(Boolean), answer }); }}><input className="form-input" required placeholder="Question" value={question} onChange={e => setQuestion(e.target.value)} /><textarea className="form-input" value={options} onChange={e => setOptions(e.target.value)} /><label>Correct option number (starting at 1)<input type="number" min="1" max="8" value={answer + 1} onChange={e => setAnswer(Number(e.target.value) - 1)} /></label><button className="btn">Launch practice quiz</button></form>}{data.quiz && <div><strong>{data.quiz.question}</strong>{data.quiz.options.map((o, i) => <button key={i} className="btn" disabled={teacher || data.quiz.closed} onClick={() => update({ action: 'answer', quizId: data.quiz.id, answer: i })}>{o}{data.quiz.myAnswer === i ? ' ✓' : ''}</button>)}{data.quiz.closed && <p>Correct answer: {data.quiz.options[data.quiz.answer]}</p>}{teacher && <><button className="btn" onClick={() => update({ action: 'closeQuiz' })}>Close/reveal answer</button><p>{Object.keys(data.quiz.responses || {}).length} answers received</p></>}</div>}
    <h4>Shared files</h4>{data.files.map((f, i) => <p key={i}><a href={f.url} target="_blank" rel="noreferrer">{f.name}</a></p>)}<input className="form-input" placeholder="File name" value={file.name} onChange={e => setFile({ ...file, name: e.target.value })} /><input className="form-input" placeholder="HTTPS file link" value={file.url} onChange={e => setFile({ ...file, url: e.target.value })} /><button className="btn" onClick={() => update({ action: 'file', ...file })}>Share file</button>
    {teacher && <><h4>Live recording</h4><p>Select this classroom browser tab and enable tab audio in the browser picker. Tab audio and your microphone are recorded when available. Stopping saves a local recording automatically.</p><button className="btn" onClick={recording ? () => recorder.current?.stop() : startRecording}>{recording ? 'Stop recording' : 'Record screen/tab'}</button>{blob && <><button className="btn" onClick={downloadRecording}>Download recording</button><button className="btn" disabled={busy} onClick={shareRecording}>{busy ? 'Uploading…' : 'Publish recording as lesson'}</button></>}</>}
  </section>;
}
