const COLORS = {
  forest: [15, 61, 46], emerald: [27, 138, 99], gold: [227, 162, 60],
  ink: [22, 34, 29], muted: [83, 101, 93], sand: [244, 241, 232], line: [221, 213, 192], white: [255, 255, 255]
};

export async function createBrandedPdf(jsPDF, { title, subtitle = '', orientation = 'portrait', subject = title } = {}) {
  const pdf = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  pdf.setProperties({ title, subject, author: 'CareerZ.pk', creator: 'CareerZ.pk' });
  const width = pdf.internal.pageSize.getWidth();
  pdf.setFillColor(...COLORS.forest); pdf.rect(0, 0, width, 34, 'F');
  pdf.setFillColor(...COLORS.gold); pdf.rect(0, 34, width, 2, 'F');
  const response = await fetch('/brand/logo-dark.png');
  if (!response.ok) throw new Error('Could not load PDF logo. Please retry.');
  const logo = await new Promise((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; response.blob().then(blob => reader.readAsDataURL(blob),reject); });
  pdf.addImage(logo, 'PNG', 10, 2, 60, 32);
  pdf.careerZLogo = logo;
  pdf.setTextColor(...COLORS.white); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(17); pdf.text('CareerZ.pk', 80, 14);
  pdf.setFont('helvetica', 'normal'); pdf.setFontSize(8); pdf.text('The Complete AI-Powered Education Ecosystem', 80, 20);
  pdf.setTextColor(...COLORS.forest); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(20); pdf.text(title || 'Document', 14, 51);
  if (subtitle) { pdf.setTextColor(...COLORS.muted); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(9); pdf.text(String(subtitle), 14, 58); }
  return pdf;
}

export function addPdfFooter(pdf) {
  const pages = pdf.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    pdf.setPage(page); if (page > 1 && pdf.careerZLogo) { pdf.setFillColor(...COLORS.forest); pdf.rect(0,0,pdf.internal.pageSize.getWidth(),15,'F'); pdf.addImage(pdf.careerZLogo,'PNG',14,0,28,15); } const width = pdf.internal.pageSize.getWidth(); const height = pdf.internal.pageSize.getHeight();
    pdf.setDrawColor(...COLORS.line); pdf.line(14, height - 14, width - 14, height - 14);
    pdf.setTextColor(...COLORS.muted); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(7.5);
    pdf.text(`Generated by CareerZ.pk  •  ${new Date().toLocaleString()}`, 14, height - 8);
    pdf.text(`Page ${page} of ${pages}`, width - 14, height - 8, { align: 'right' });
  }
}

export function drawPdfTable(pdf, { headers, rows, startY = 68, widths } = {}) {
  const margin = 14; const pageWidth = pdf.internal.pageSize.getWidth(); const pageHeight = pdf.internal.pageSize.getHeight();
  const usable = pageWidth - margin * 2; const columnWidths = widths || headers.map(() => usable / headers.length);
  let y = startY;
  const header = () => {
    pdf.setFillColor(...COLORS.forest); pdf.roundedRect(margin, y, usable, 10, 2, 2, 'F');
    pdf.setTextColor(...COLORS.white); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(8);
    let x = margin; headers.forEach((value, index) => { pdf.text(String(value), x + 3, y + 6.4, { maxWidth: columnWidths[index] - 6 }); x += columnWidths[index]; }); y += 10;
  };
  header();
  rows.forEach((row, rowIndex) => {
    const cells = row.map((value, index) => pdf.splitTextToSize(String(value ?? '—'), Math.max(10, columnWidths[index] - 6)));
    const rowHeight = Math.max(10, ...cells.map((lines) => lines.length * 4 + 4));
    if (y + rowHeight > pageHeight - 20) { pdf.addPage(); y = 18; header(); }
    pdf.setFillColor(...(rowIndex % 2 ? COLORS.sand : COLORS.white)); pdf.rect(margin, y, usable, rowHeight, 'F');
    pdf.setDrawColor(...COLORS.line); pdf.line(margin, y + rowHeight, margin + usable, y + rowHeight);
    pdf.setTextColor(...COLORS.ink); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(8);
    let x = margin; cells.forEach((lines, index) => { pdf.text(lines, x + 3, y + 6); x += columnWidths[index]; }); y += rowHeight;
  });
  return y;
}

export function drawPdfSummary(pdf, items, startY = 68) {
  const width = pdf.internal.pageSize.getWidth() - 28; const column = width / 2; let y = startY;
  items.forEach((item, index) => {
    const x = 14 + (index % 2) * column;
    if (index > 0 && index % 2 === 0) y += 18;
    pdf.setFillColor(...COLORS.sand); pdf.roundedRect(x, y, column - 3, 14, 2, 2, 'F');
    pdf.setTextColor(...COLORS.muted); pdf.setFontSize(7); pdf.setFont('helvetica', 'bold'); pdf.text(String(item.label).toUpperCase(), x + 4, y + 5);
    pdf.setTextColor(...COLORS.ink); pdf.setFontSize(10); pdf.text(String(item.value ?? '—'), x + 4, y + 11, { maxWidth: column - 11 });
  });
  return y + 18;
}

export { COLORS as PDF_COLORS };
