import {useEffect,useState} from 'react';
import {apiRequest} from '../../api/client';
export function FamilyPolicy({onFlash}){
 const [schools,setSchools]=useState([]),[id,setId]=useState(''),[policy,setPolicy]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{apiRequest('/institutions/mine/list').then(rows=>{setSchools(rows);setId(rows[0]?._id||'');}).catch(e=>onFlash(e.message));},[]);
 useEffect(()=>{let active=true;setPolicy(null);if(id)apiRequest(`/institutions/${id}/family/policy`).then(p=>{if(active)setPolicy(p);}).catch(e=>onFlash(e.message));return()=>{active=false;};},[id]);
 return <section className="admin-card"><h2>Guardian support policy</h2>{schools.length>1&&<label>Institution<select className="form-select" value={id} disabled={busy} onChange={e=>setId(e.target.value)}>{schools.map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select></label>}{policy&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{setPolicy(await apiRequest(`/institutions/${id}/family/policy`,{method:'PUT',body:policy}));onFlash('Guardian policy saved.','success');}catch(err){onFlash(err.message);}finally{setBusy(false);}}}><label style={{display:'block'}}><input type="checkbox" disabled={busy} checked={policy.parentAiEnabled} onChange={e=>setPolicy({...policy,parentAiEnabled:e.target.checked})}/> Allow approved parents to use this institution’s connected AI provider for their child’s records at this school (owner authorization required)</label><p>Parents must consent before each request. Provider charges use the institution’s own connected account; records from other schools are excluded.</p><label>Persistent absence warning threshold (distinct days in 30 days)<input className="form-input" type="number" min={5} max={30} required disabled={busy} value={policy.dropoutAbsenceDays} onChange={e=>setPolicy({...policy,dropoutAbsenceDays:Number(e.target.value)})}/></label><button className="btn btn-primary" disabled={busy}>Save guardian policy</button></form>}</section>;
}
export function StudentFamilyMeeting({onFlash}){
 const [teachers,setTeachers]=useState([]),[teacherId,setTeacher]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{apiRequest('/parents/student/teachers').then(setTeachers).catch(e=>onFlash(e.message));},[]);
 return <section className="admin-card"><h2>Ask your guardian to arrange a meeting</h2><p>Your approved guardians receive your request and can book a time with your current teacher.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apiRequest('/parents/student/ptm-invitation',{method:'POST',body:{teacherId,note}});setNote('');onFlash('Meeting invitation sent to your guardians.','success');}catch(err){onFlash(err.message);}finally{setBusy(false);}}}><label>Teacher<select className="form-select" required disabled={busy} value={teacherId} onChange={e=>setTeacher(e.target.value)}><option value="">Choose your teacher</option>{teachers.map(t=><option key={t.teacher._id} value={t.teacher._id}>{t.teacher.fullName} · {t.subjects.join(', ')}</option>)}</select></label><label>Reason or note<textarea className="form-input" maxLength={1000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||!teacherId}>Send meeting invitation</button></form></section>;
}
