import GuardianProof from './GuardianProof';
import { useEffect, useState } from 'react';
import { apiRequest } from '../../api/client';
import { createBrandedPdf, drawPdfTable, addPdfFooter } from '../../utils/brandedPdf';

const grid={display:'grid',gap:16,gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))'};
const card={padding:20,border:'1px solid var(--sand-line)',borderRadius:18,background:'var(--white,white)'};
const date=v=>v?new Date(v).toLocaleDateString():'—';
async function download(title,subtitle,headers,rows){const {jsPDF}=await import('jspdf');const pdf=await createBrandedPdf(jsPDF,{title,subtitle});drawPdfTable(pdf,{headers,rows});addPdfFooter(pdf);pdf.save(title.toLowerCase().replaceAll(' ','-')+'.pdf');}
function Rows({headers,rows}){return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{headers.map(h=><th key={h} style={{textAlign:'left',padding:12,background:'var(--sand)'}}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} style={{padding:12,borderBottom:'1px solid var(--sand-line)'}}>{v??'—'}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No records yet.</p>}</div>;}

export function FamilyConnections({student=false,onFlash}){
 const [rows,setRows]=useState(null),[target,setTarget]=useState(''),[relationship,setRelationship]=useState('guardian'),[busy,setBusy]=useState(false),[incoming,setIncoming]=useState([]);
 async function load(){const [r,i]=await Promise.all([apiRequest('/parents/link-requests'),apiRequest('/parents/incoming-requests')]);setRows(r);setIncoming(i);}
 useEffect(()=>{load().catch(e=>onFlash(e.message));},[student]);
 async function run(fn){setBusy(true);try{await fn();await load();onFlash('Connection updated.','success');}catch(e){onFlash(e.message);}finally{setBusy(false);}}
 return <section><h2>{student?'Parent Connections':'My Children'}</h2><form style={{...card,...grid}} onSubmit={e=>{e.preventDefault();run(async()=>{await apiRequest('/parents/link-requests',{method:'POST',body:{...(student?(target.includes('@')?{parentEmail:target}:{parentMobile:target}):{studentEmail:target}),relationship}});setTarget('');});}}>
 <label>{student?'Parent email or registered mobile':'Child account email'}<input className="form-input" required value={target} onChange={e=>setTarget(e.target.value)} type={student?'text':'email'}/></label><label>Relationship<select className="form-select" value={relationship} onChange={e=>setRelationship(e.target.value)}>{['father','mother','guardian','sponsor'].map(r=><option key={r}>{r}</option>)}</select></label><button className="btn btn-primary" disabled={busy}>Send invitation</button></form>
 {rows===null?<p role="status">Loading connections…</p>:<div style={{...grid,marginTop:18}}>{rows.map(r=><article key={r._id} style={card}><h3>{student?r.parent?.fullName:r.student?.fullName}</h3>{!student&&r.student?.profilePhoto&&<img src={r.student.profilePhoto} alt={r.student.fullName} style={{width:64,height:64,borderRadius:'50%',objectFit:'cover'}}/>}<p>{r.relationship} · {r.status}</p>{r.childDetails&&<p>{r.childDetails.className||r.childDetails.program} · Roll {r.childDetails.rollNumber||'not assigned'}{r.childDetails.age!==null?` · Age ${r.childDetails.age}`:''}<br/>{r.childDetails.institutions.map(i=>i.name).join(' · ')}</p>}{incoming.some(i=>i._id===r._id)&&<div><button className="btn" disabled={busy} onClick={()=>run(()=>apiRequest(`/parents/link-requests/${r._id}/respond`,{method:'PATCH',body:{decision:'approved'}}))}>Approve</button> <button className="btn" disabled={busy} onClick={()=>run(()=>apiRequest(`/parents/link-requests/${r._id}/respond`,{method:'PATCH',body:{decision:'rejected'}}))}>Reject</button></div>}
 {!student&&r.status==='approved'&&r.relationship!=='sponsor'&&(r.childDetails?.institutions||[]).map(i=><div key={i._id}><strong>{i.name}</strong><GuardianProof linkId={r._id} institutionId={i._id} onFlash={onFlash}/></div>)}{student&&r.status==='approved'&&['payFees','viewHealth','giveConsent','observeClassroom'].map(key=><label key={key} style={{display:'block',margin:'8px 0'}}><input type="checkbox" disabled={busy||(r.relationship==='sponsor'&&key!=='payFees')} checked={!(r.relationship==='sponsor'&&key!=='payFees')&&r.permissions?.[key]!==false} onChange={e=>run(()=>apiRequest(`/parents/link-requests/${r._id}/permissions`,{method:'PATCH',body:{[key]:e.target.checked}}))}/> {({payFees:'Pay fees',viewHealth:'Health access',giveConsent:'Sign consent',observeClassroom:'Observe classroom'})[key]}</label>)}
 {r.status!=='revoked'&&<button className="btn" disabled={busy} onClick={()=>run(()=>apiRequest(`/parents/link-requests/${r._id}`,{method:'DELETE'}))}>{r.status==='approved'?'Remove connection':'Remove request'}</button>}<details><summary>Connection history</summary>{(r.lifecycleHistory||[]).map((h,i)=><p key={i}>{h.action} · {date(h.at)}</p>)}</details></article>)}{!rows.length&&<p>No family connections yet.</p>}</div>}</section>;
}

export function FamilyAcademic({kind='performance',onFlash}){
 const [children,setChildren]=useState([]),[child,setChild]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[signature,setSignature]=useState(''),[school,setSchool]=useState(''),[term,setTerm]=useState('');
 useEffect(()=>{apiRequest('/parents/children').then(r=>{setChildren(r);setChild(r[0]?.student?._id||'');}).catch(e=>setError(e.message));},[]);
 async function load(){if(!child)return;setError('');try{setData(await apiRequest(`/parents/children/${child}/overview?month=${month}`));}catch(e){setError(e.message);}}
 useEffect(()=>{let active=true;setData(null);setError('');if(child)apiRequest(`/parents/children/${child}/overview?month=${month}`).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[child,month]);
 const subtitle=data?data.student.fullName+' · '+(data.profile?.rollNumber||'')+' · '+month:'';
 const filteredResults=(data?.results||[]).filter(r=>(!school||String(r.institution?._id||r.institution)===school)&&(!term||[r.academicSession,r.term].join(' / ')===term));
 const resultHeaders=['Session / Term','Subject','Marks','Grade','Institution'];const resultRows=filteredResults.map(r=>[r.academicSession||r.term,r.subject,`${r.marksObtained}/${r.totalMarks}`,r.grade,r.institution?.name]);
 const attendanceHeaders=['Date','Status','Reason'];const attendanceRows=(data?.attendance||[]).map(r=>[date(r.date),r.status?.replaceAll('_',' '),r.reason]);
 return <section><div style={{...grid,marginBottom:20}}><label>Child<select className="form-select" value={child} onChange={e=>{setChild(e.target.value);setSchool('');setTerm('');setSignature('');}}>{children.map(c=><option key={c._id} value={c.student._id}>{c.student.fullName}</option>)}</select></label>{['attendance','performance'].includes(kind)&&<label>Month<input className="form-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}</div>
 {error&&<p role="alert">{error}</p>}{!child&&<p>Link a child to start.</p>}{child&&!data&&!error&&<p role="status">Loading child records…</p>}
 {data&&<><div style={{...card,marginBottom:20}}><h3>{data.student.fullName}</h3><p>{data.profile?.classSection?.name} · {data.profile?.program} · Roll {data.profile?.rollNumber||'not assigned'}</p><p>{data.institutions.map(i=>i.name).join(' · ')}</p></div>
 {['attendance','performance'].includes(kind)&&<><div style={grid}>{Object.entries(data.attendanceTotals).map(([k,v])=><div style={card} key={k}><strong>{k.replaceAll('_',' ')}</strong><p style={{fontSize:28,margin:8}}>{v}</p><meter min="0" max={Math.max(1,data.attendance.length)} value={v} aria-label={k}/></div>)}</div><button className="btn" style={{margin:'16px 0'}} onClick={()=>download('Attendance report',subtitle,attendanceHeaders,attendanceRows).catch(e=>onFlash(e.message))}>Download attendance PDF</button><Rows headers={attendanceHeaders} rows={attendanceRows}/></>}
 {['results','performance'].includes(kind)&&<><h3>Academic progress</h3><div style={grid}><label>Institution<select className="form-select" value={school} onChange={e=>setSchool(e.target.value)}><option value="">All institutions</option>{data.institutions.map(i=><option key={i._id} value={i._id}>{i.name}</option>)}</select></label><label>Session / Term<select className="form-select" value={term} onChange={e=>setTerm(e.target.value)}><option value="">All sessions / terms</option>{[...new Set(data.results.map(r=>[r.academicSession,r.term].join(' / ')))].map(t=><option key={t}>{t}</option>)}</select></label></div><button className="btn" onClick={()=>download('Report card',data.student.fullName+' · '+(school?data.institutions.find(i=>i._id===school)?.name:'All institutions')+' · '+(term||'All recorded sessions'),resultHeaders,resultRows).catch(e=>onFlash(e.message))}>Download report card PDF</button><Rows headers={resultHeaders} rows={resultRows}/><div style={{...grid,marginTop:16}}>{data.subjects.filter(s=>(!school||String(s.institution)===school)&&(!term||[s.session,s.term].join(' / ')===term)).map((s,i)=><article style={card} key={i}><strong>{s.subject}</strong><p>{s.session||s.term}</p><meter min="0" max="100" value={s.percentage} style={{width:'100%'}}/><p>{s.percentage}% · {s.percentage>=75?'Strong area':s.percentage<50?'Needs support':'Developing'}</p></article>)}</div><h3>Rank among graded classmates</h3><Rows headers={['Subject','Session / Term','Rank','Graded students']} rows={(data.ranks||[]).filter(r=>(!school||String(r.institution)===school)&&(!term||[r.session,r.term].join(' / ')===term)).map(r=>[r.subject,[r.session,r.term].filter(Boolean).join(' / '),r.rank,r.gradedStudents])}/><h3>Teacher feedback & improvement</h3>{data.behavior.map(r=><article style={card} key={r._id}><strong>{r.type} · {r.actor?.fullName} · {date(r.createdAt)}</strong><p>{r.text}</p></article>)}{!data.behavior.length&&<p>No teacher notes yet.</p>}</>}
 {kind==='timetable'&&<Rows headers={['Institution','Day','Time','Subject','Teacher','Room / Online']} rows={data.timetable.map(t=>[t.institution?.name,t.dayOfWeek,t.startTime+'–'+t.endTime,t.subject,t.teacher?.fullName,t.meetingLink?<a href={t.meetingLink} target="_blank" rel="noreferrer">Meeting link</a>:t.room])}/>}
 {kind==='portfolio'&&<><h3>Student ID</h3><p>{data.student.fullName} · {data.profile?.rollNumber}</p>{data.profile?.idCardCode&&<a className="btn" href={`/verify-student-id/${data.profile.idCardCode}`} target="_blank" rel="noreferrer">View verified student ID</a>}<h3>Certificates</h3>{data.certificates.map(c=><article key={c._id} style={card}><strong>{c.title}</strong><p>{c.institution?.name} · {date(c.issueDate)}</p>{c.verifyCode&&<a href={`/verify-certificate/${c.verifyCode}`} target="_blank" rel="noreferrer">View certificate verification</a>}{c.verifyCode&&<button className="btn" onClick={()=>download('Certificate',data.student.fullName,['Field','Value'],[['Award',c.title],['Institution',c.institution?.name],['Issued',date(c.issueDate)],['Verification',window.location.origin+'/verify-certificate/'+c.verifyCode]]).catch(e=>onFlash(e.message))}>Download certificate PDF</button>}</article>)}<h3>Awards & achievements</h3>{data.achievements.map(a=><article style={card} key={a._id}><strong>{a.title}</strong><p>{a.description} · {a.verificationStatus}</p>{/^https:\/\//.test(a.evidenceUrl||'')&&<a href={a.evidenceUrl} target="_blank" rel="noreferrer">View evidence</a>}</article>)}<h3>Library records</h3><Rows headers={['Book','Due','Status','Fine']} rows={data.libraryLoans.map(l=>[l.book?.title,date(l.dueDate),l.status,l.fineAmount])}/></>}
 {kind==='permissions'&&<><h3>Institution permission requests</h3><label>Your full name for digital signature<input className="form-input" value={signature} onChange={e=>setSignature(e.target.value)}/></label>{data.consentRequests.map(r=><article style={{...card,marginTop:14}} key={r._id}><h3>{r.title}</h3><p>{r.institution?.name} · {r.type} · {r.status} · Expires {date(r.expiresAt)}</p><p>{r.details}</p>{r.response&&<p>{r.response.decision} by {r.response.signedName} on {date(r.response.signedAt)}</p>}{r.status==='open'&&(!r.expiresAt||new Date(r.expiresAt)>new Date())&&['granted','denied'].map(decision=><button className="btn" key={decision} disabled={busy||!signature.trim()} onClick={async()=>{setBusy(true);try{await apiRequest(`/parents/consent-requests/${r._id}/respond`,{method:'POST',body:{decision,signedName:signature}});await load();onFlash('Signed response saved.','success');}catch(e){onFlash(e.message);}finally{setBusy(false);}}}>{decision==='granted'?'Grant / update permission':'Deny / withdraw permission'}</button>)}</article>)}{!data.consentRequests.length&&<p>No permission requests from your institutions.</p>}</>}
 </>}</section>;
}

export function FamilyPayments({onFlash}){
 const [data,setData]=useState(null),[fees,setFees]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[amounts,setAmounts]=useState({}),[requests,setRequests]=useState({});
 function load(){return Promise.all([apiRequest('/parents/wallet'),apiRequest('/parents/children').then(async list=>(await Promise.all(list.map(c=>apiRequest(`/parents/children/${c.student._id}/fees`).then(rows=>rows.map(f=>({...f,childName:c.student.fullName})))))).flat())]).then(([w,f])=>{setData(w);setFees(f);}).catch(e=>setError(e.message));}
 useEffect(()=>{load();},[]);
 const entries=fees.flatMap(f=>(f.paymentHistory?.length?f.paymentHistory:f.status==='paid'?[{amount:f.paidAmount||f.amount,verifiedAt:f.paidAt,method:f.paidVia,receiptNumber:f.receiptNumber,transactionId:f.transactionId}]:[]).filter(p=>p.verificationStatus==='verified'||p.verifiedAt).map(p=>({fee:f,payment:p})));
 return <section><h2>Wallet & Payment Records</h2>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Loading…</p>}{data&&<><div style={grid}>{data.balances.map(b=><article key={b._id} style={card}><strong>{b.currency} wallet</strong><p>Available {b.available} · Pending {b.pending}</p></article>)}</div>{!data.balances.length&&<p>No wallet balance yet.</p>}<h3>Pay child invoices from wallet</h3>{fees.filter(f=>['pending','overdue','partially_paid'].includes(f.status)).map(f=><form key={f._id} style={{...card,marginTop:12,...grid}} onSubmit={async e=>{e.preventDefault();const requestId=requests[f._id]||crypto.randomUUID();setRequests(r=>({...r,[f._id]:requestId}));setBusy(true);try{await apiRequest(`/parents/fees/${f._id}/wallet-payment`,{method:'POST',body:{amount:Number(amounts[f._id]||f.outstandingAmount||Math.max(0,f.amount-(f.paidAmount||0))),requestId}});setRequests(r=>({...r,[f._id]:undefined}));await load();onFlash('Wallet payment verified.','success');}catch(e){onFlash(e.message);}finally{setBusy(false);}}}><div><strong>{f.childName} · {f.institution?.name}</strong><p>{f.title} · Due {date(f.dueDate)}</p><p>Outstanding {f.currency} {f.outstandingAmount??Math.max(0,f.amount-(f.paidAmount||0))}</p></div><label>Amount<input className="form-input" type="number" min="0.01" step="0.01" disabled={busy} required value={amounts[f._id]??f.outstandingAmount??Math.max(0,f.amount-(f.paidAmount||0))} onChange={e=>{setAmounts(r=>({...r,[f._id]:e.target.value}));setRequests(r=>({...r,[f._id]:undefined}));}}/></label><button className="btn btn-primary" disabled={busy}>Pay from {f.currency} wallet</button></form>)}<h3>Wallet transactions</h3><Rows headers={['Date','Type','Amount','Status','Reference']} rows={data.transactions.map(t=>[date(t.createdAt),t.type,t.currency+' '+t.amount,t.status,t.reference])}/><h3>Verified fee payments</h3>{entries.map(({fee:f,payment:p},i)=><article style={{...card,marginTop:12}} key={i}><strong>{f.childName} · {f.institution?.name} · {f.title}</strong><p>{f.currency} {p.amount} · {date(p.verifiedAt||p.paidAt)} · {p.method}</p><button className="btn" onClick={()=>download('Payment receipt',f.childName,['Item','Value'],[['Institution',f.institution?.name],['Invoice',f.title],['Amount',f.currency+' '+p.amount],['Paid on',date(p.verifiedAt||p.paidAt)],['Method',p.method],['Receipt',p.receiptNumber||p.transactionId]]).catch(e=>onFlash(e.message))}>Download receipt PDF</button></article>)}</>}</section>;
}

export function InstitutionFamilyActions({onFlash}){
 const [institutions,setInstitutions]=useState([]),[institution,setInstitution]=useState(''),[rows,setRows]=useState([]),[students,setStudents]=useState([]),[observationEnabled,setObservationEnabled]=useState(false),[form,setForm]=useState({studentId:'',type:'trip',title:'',details:'',expiresAt:''}),[busy,setBusy]=useState(false);
 useEffect(()=>{apiRequest('/institutions/mine/list').then(r=>{setInstitutions(r);setInstitution(r[0]?._id||'');}).catch(e=>onFlash(e.message));},[]);
 async function load(){if(institution){const [requests,roster,policy]=await Promise.all([apiRequest(`/institutions/${institution}/family/consent-requests`),apiRequest(`/institutions/${institution}/students`),apiRequest(`/institutions/${institution}/family/observation-policy`)]);setRows(requests);setStudents(roster);setObservationEnabled(policy.enabled);}}
 useEffect(()=>{load().catch(e=>onFlash(e.message));},[institution]);
 return <section style={{...card,marginTop:22}}><h2>Guardian Permission Requests</h2><label style={{display:'block',marginBottom:16}}><input type="checkbox" disabled={busy||!institution} checked={observationEnabled} onChange={async e=>{setBusy(true);try{const policy=await apiRequest(`/institutions/${institution}/family/observation-policy`,{method:'PUT',body:{enabled:e.target.checked}});setObservationEnabled(policy.enabled);onFlash('Classroom observation policy updated.','success');}catch(e){onFlash(e.message);}finally{setBusy(false);}}}/> Allow approved guardians to observe online classes with their child's permission</label><label>Institution<select className="form-select" value={institution} onChange={e=>setInstitution(e.target.value)}>{institutions.map(i=><option key={i._id} value={i._id}>{i.name}</option>)}</select></label><form style={{...grid,marginTop:16}} onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apiRequest(`/institutions/${institution}/family/consent-requests`,{method:'POST',body:{...form,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null}});await load();onFlash('Guardian request sent.','success');}catch(err){onFlash(err.message);}finally{setBusy(false);}}}><label>Student<select className="form-select" required value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})}><option value="">Choose student</option>{students.filter(s=>s.user).map(s=><option key={s._id} value={s.user._id}>{s.user.fullName} {s.rollNumber?`(${s.rollNumber})`:''}</option>)}</select></label>{['title','details','expiresAt'].map(k=><label key={k}>{({studentId:'Student account ID',title:'Activity title',details:'Details',expiresAt:'Expires at'})[k]}<input className="form-input" required={['studentId','title'].includes(k)} type={k==='expiresAt'?'datetime-local':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Type<select className="form-select" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['trip','event','competition','photo','medical','other'].map(t=><option key={t}>{t}</option>)}</select></label><button className="btn" disabled={busy||!institution}>Request permission</button></form>{rows.map(r=><article key={r._id} style={{marginTop:16}}><strong>{r.student?.fullName} · {r.title} · {r.status}</strong><p>{(r.responses||[]).map(p=>p.parent?.fullName+': '+p.decision+' ('+p.signedName+')').join(' · ')||'Awaiting guardian response'}</p>{r.status==='open'&&<button className="btn" onClick={async()=>{try{await apiRequest(`/institutions/family/consent-requests/${r._id}/cancel`,{method:'PATCH'});await load();}catch(e){onFlash(e.message);}}}>Cancel request</button>}</article>)}</section>;
}

export function FamilyTeacherNotes({onFlash}){
 const [roster,setRoster]=useState([]),[chosen,setChosen]=useState(''),[type,setType]=useState('progress'),[text,setText]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{apiRequest('/parents/teaching-roster').then(setRoster).catch(e=>onFlash(e.message));},[]);
 const rows=[...new Map(roster.map(r=>[r.student._id+':'+r.institution,r])).values()];
 return <section style={{...card,marginTop:20}}><h2>Child progress & guardian updates</h2><p>Send an improvement note to the child's approved guardians.</p><form style={grid} onSubmit={async e=>{e.preventDefault();const r=rows.find(r=>r.student._id+':'+r.institution===chosen);if(!r)return;setBusy(true);try{await apiRequest(`/institutions/${r.institution}/family/observations`,{method:'POST',body:{studentId:r.student._id,type,text}});setText('');onFlash('Guardian update saved and sent.','success');}catch(e){onFlash(e.message);}finally{setBusy(false);}}}><label>Student<select className="form-select" required value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose student</option>{rows.map(r=><option key={r.student._id+':'+r.institution} value={r.student._id+':'+r.institution}>{r.student.fullName} · {r.course}</option>)}</select></label><label>Update type<select className="form-select" value={type} onChange={e=>setType(e.target.value)}>{['progress','behavior','discipline','emergency','achievement'].map(t=><option key={t}>{t}</option>)}</select></label><label>Notes<textarea className="form-input" required maxLength={5000} value={text} onChange={e=>setText(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||!chosen}>Send guardian update</button></form></section>;
}
