import {useEffect,useState} from 'react';
import {apiRequest} from '../../api/client';
const grid={display:'grid',gap:16,gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))'},card={border:'1px solid var(--sand-line)',borderRadius:18,padding:20};
export default function FamilyCafeteria({onFlash,institution=false,studentId:ownStudent}){
 const [choices,setChoices]=useState([]),[scope,setScope]=useState(''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[quantities,setQuantities]=useState({}),[keys,setKeys]=useState({}),[edit,setEdit]=useState(null),[form,setForm]=useState({name:'',description:'',allergens:'',price:'',currency:'PKR',stock:'',active:true});
 const path=institution?`/institutions/${scope}/cafeteria`:`/parents/children/${scope}/cafeteria`;
 useEffect(()=>{if(ownStudent){setScope(ownStudent);return;}apiRequest(institution?'/institutions/mine/list':'/parents/children').then(rows=>{const opts=rows.map(r=>institution?r:{_id:r.student._id,name:r.student.fullName});setChoices(opts);setScope(opts[0]?._id||'');}).catch(e=>onFlash(e.message));},[institution,ownStudent]);
 useEffect(()=>{let active=true;setData(null);if(scope)apiRequest(path).then(r=>{if(active)setData(r);}).catch(e=>{if(active)onFlash(e.message);});return()=>{active=false;};},[scope,institution]);
 async function act(fn){setBusy(true);try{await fn();setData(await apiRequest(path));onFlash('Cafeteria updated.','success');}catch(e){onFlash(e.message);}finally{setBusy(false);}}
 return <section><h2>{institution?'School cafeteria':'Child cafeteria'}</h2><p>{institution?'Manage menu stock, paid orders and verified collection.':'Purchase food using your wallet. The child receives a pickup code; review allergens before ordering.'}</p>{choices.length>1&&<label>{institution?'Institution':'Child'}<select className="form-select" disabled={busy} value={scope} onChange={e=>setScope(e.target.value)}>{choices.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label>}
 {!scope?<p>No {institution?'managed institutions':'linked children'} yet.</p>:!data?<p role="status">Loading cafeteria…</p>:<>
 {institution&&<form style={card} onSubmit={e=>{e.preventDefault();act(async()=>{await apiRequest(path+'/items'+(edit?'/'+edit:''),{method:edit?'PUT':'POST',body:{...form,price:Number(form.price),stock:Number(form.stock)}});setEdit(null);setForm({name:'',description:'',allergens:'',price:'',currency:'PKR',stock:'',active:true});});}}><h3>{edit?'Edit menu item':'Add menu item'}</h3><div style={grid}>{[['name','Item name'],['description','Description'],['allergens','Allergens'],['price','Price'],['currency','Currency'],['stock','Available portions']].map(([k,label])=><label key={k}>{label}<input className="form-input" disabled={busy} required={['name','price','currency','stock'].includes(k)} type={['price','stock'].includes(k)?'number':'text'} min={k==='price'?0.01:0} step={k==='price'?0.01:k==='stock'?1:undefined} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label><input type="checkbox" disabled={busy} checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Available on menu</label> <button className="btn btn-primary" disabled={busy}>Save item</button>{edit&&<button type="button" className="btn" disabled={busy} onClick={()=>setEdit(null)}>Cancel edit</button>}</form>}
 <h3>Menu</h3><div style={grid}>{data.items.map(i=><article key={i._id} style={card}><h3>{i.name}</h3><p>{i.institution?.name}</p><p>{i.description}</p><p>Allergens: {i.allergens||'Not listed — check with the cafeteria'}</p><p>{i.currency} {i.price} · {i.stock} portions {i.active?'available':'(hidden)'}</p>{institution?<button className="btn" disabled={busy} onClick={()=>{setEdit(i._id);setForm({name:i.name,description:i.description||'',allergens:i.allergens||'',price:i.price,currency:i.currency,stock:i.stock,active:i.active});}}>Edit item</button>:!ownStudent&&<form onSubmit={e=>{e.preventDefault();const key=keys[i._id]||crypto.randomUUID();setKeys(prev=>({...prev,[i._id]:key}));act(async()=>{await apiRequest(path+'/orders',{method:'POST',body:{itemId:i._id,quantity:Number(quantities[i._id]||1),requestId:key}});setKeys(prev=>({...prev,[i._id]:null}));});}}><label>Quantity<input className="form-input" type="number" min={1} max={Math.min(20,i.stock)} value={quantities[i._id]||1} disabled={busy||!i.stock} onChange={e=>{setQuantities({...quantities,[i._id]:e.target.value});setKeys({...keys,[i._id]:null});}}/></label><button className="btn btn-primary" disabled={busy||!i.stock}>Pay {i.currency} {(i.price*Number(quantities[i._id]||1)).toFixed(2)}</button></form>}</article>)}</div>{!data.items.length&&<p>The institution has not published a menu.</p>}
 <h3>{institution?'Paid orders':'Orders and pickup codes'}</h3><div style={grid}>{data.orders.map(o=><article key={o._id} style={card}><h3>{o.itemName} × {o.quantity}</h3><p>{o.student?.fullName||o.institution?.name} · {o.currency} {o.total} · {o.status}</p><p>{new Date(o.createdAt).toLocaleString()}</p>{o.status==='paid'&&<p>Pickup code: <strong>{o.pickupCode}</strong></p>}{institution&&o.status==='paid'&&<form onSubmit={e=>{e.preventDefault();const code=new FormData(e.currentTarget).get('code');act(()=>apiRequest(`/institutions/cafeteria/orders/${o._id}`,{method:'PATCH',body:{decision:'fulfilled',pickupCode:code}}));}}><label>Confirm child’s pickup code<input className="form-input" name="code" required disabled={busy}/></label><button className="btn" disabled={busy}>Mark collected</button></form>}{!ownStudent&&o.status!=='refunded'&&(institution||o.status==='paid')&&<form onSubmit={e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');act(()=>apiRequest(`/${institution?'institutions':'parents'}/cafeteria/orders/${o._id}`,{method:'PATCH',body:{decision:'refunded',reason}}));}}><label>Refund reason<input className="form-input" name="reason" required maxLength={1000} disabled={busy}/></label><button className="btn" disabled={busy}>{institution?'Refund order':'Cancel and refund'}</button></form>}{o.refundReason&&<p>Refund: {o.refundReason}</p>}</article>)}</div>{!data.orders.length&&<p>No cafeteria orders yet.</p>}</>}
 </section>;
}
