import {useState} from 'react';
import {apiRequest} from '../../api/client';
export default function GuardianProof({linkId,institutionId,review=false,onFlash,onDone}){
 const [proof,setProof]=useState(null),[files,setFiles]=useState({}),[busy,setBusy]=useState(false),[notes,setNotes]=useState(''),[matched,setMatched]=useState(false);
 const url=`/parents/links/${linkId}/schools/${institutionId}/proof`;
 async function run(fn){setBusy(true);try{await fn();onDone?.();}catch(e){onFlash(e.message);}finally{setBusy(false);}}
 async function load(){setProof(await apiRequest(url));}
 return <details style={{padding:12,border:'1px solid var(--sand-line)',borderRadius:12,margin:'10px 0'}} onToggle={e=>{if(e.currentTarget.open)run(load);}}><summary>Guardian relationship documents</summary><p>Student approval connects accounts. School verification requires guardian ID and relationship proof matched against admission records.</p><p>Status: {proof?.status||'Not submitted'} {proof?.reason&&`— ${proof.reason}`}</p>
 {!review&&<form onSubmit={e=>{e.preventDefault();run(async()=>{const documents=await Promise.all(['guardian_id','relationship_proof'].map(async kind=>{const f=files[kind];if(!f||f.size>1.5*1024*1024)throw Error('Choose both documents, maximum 1.5 MB each.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f);});return {kind,name:f.name,mime:f.type,data};}));await apiRequest(url,{method:'PUT',body:{documents}});await load();onFlash('Documents submitted for school review.','success');});}}>{['guardian_id','relationship_proof'].map(kind=><label key={kind} style={{display:'block',margin:10}}>{kind==='guardian_id'?'Guardian CNIC / identity document':'Child B-Form, birth certificate or legal guardianship proof'}<input required type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>setFiles({...files,[kind]:e.target.files[0]})}/></label>)}<button className="btn btn-primary" disabled={busy}>Submit private documents</button></form>}
 {review&&proof&&<><p>Review both documents; confirm the guardian identity and child relationship using your admission record. Files are private to this parent and authorized school reviewers.</p>{proof.documents.map(d=><button className="btn" key={d.kind} disabled={busy} onClick={()=>{const bytes=Uint8Array.from(atob(d.data),c=>c.charCodeAt(0));const u=URL.createObjectURL(new Blob([bytes],{type:d.mime}));const a=document.createElement('a');a.href=u;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}}>Download {d.kind==='guardian_id'?'guardian ID':'relationship proof'}</button>)}{proof.status==='pending'&&<><label style={{display:'block'}}><input type="checkbox" checked={matched} onChange={e=>setMatched(e.target.checked)}/> Identity and relationship match our admission records</label><label>Review notes<textarea className="form-input" maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{['approved','rejected'].map(decision=><button key={decision} className="btn" disabled={busy||!notes.trim()||decision==='approved'&&!matched} onClick={()=>run(async()=>{await apiRequest(url+'/review',{method:'POST',body:{decision,reason:notes,admissionMatched:matched}});await load();onFlash('Guardian review recorded.','success');})}>{decision==='approved'?'Approve verified guardian':'Reject proof'}</button>)}</>}</>}
 </details>;
}
