import { useState } from 'react';
import { codingDocument } from '../../utils/codingPractice';
function Activity({ activity: a }) {
  const [answers, setAnswers] = useState({}), [checked, setChecked] = useState(false), [flip, setFlip] = useState({}), [items, setItems] = useState(() => [...(a.content.items || [])].reverse()), [code, setCode] = useState(a.content.starter || 'console.log("Hello");'), [run, setRun] = useState('');
  const c = a.content;
  return <article style={{ padding: 12, border: '1px solid var(--sand-line)', margin: '12px 0' }}><h4>{a.title}</h4><p>Practice activity — does not replace a graded exam or assignment.</p>
    {a.type === 'quiz' && <>{c.questions.map((q, n) => <div key={n}><strong>{q.question}</strong>{q.options.map((o, i) => <label key={i} style={{ display: 'block' }}><input type="radio" name={`${a._id}-${n}`} checked={answers[n] === i} onChange={() => { setAnswers({ ...answers, [n]: i }); setChecked(false); }} />{o}</label>)}{checked && <p>{answers[n] === q.answer ? 'Correct' : `Correct answer: ${q.options[q.answer]}`}</p>}</div>)}<button className="btn" onClick={() => setChecked(true)}>Check answers</button></>}
    {a.type === 'flashcards' && c.cards.map((card, n) => <button className="btn" key={n} onClick={() => setFlip({ ...flip, [n]: !flip[n] })}>{flip[n] ? card.back : card.front}</button>)}
    {a.type === 'sorting' && <>{items.map((item, n) => <div key={item} draggable onDragStart={e => e.dataTransfer.setData('text/plain', String(n))} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const from = Number(e.dataTransfer.getData('text/plain')); if (!Number.isInteger(from) || from < 0 || from >= items.length) return; const next = [...items]; next.splice(n, 0, next.splice(from, 1)[0]); setItems(next); setChecked(false); }}><span>{item}</span> <button className="btn" disabled={n === 0} onClick={() => { const next = [...items]; [next[n - 1], next[n]] = [next[n], next[n - 1]]; setItems(next); setChecked(false); }}>Move up</button></div>)}<button className="btn" onClick={() => setChecked(true)}>Check order</button>{checked && <p>{items.every((v, i) => v === c.items[i]) ? 'Correct order' : 'Try again'}</p>}</>}
    {a.type === 'coding' && <><p>{c.instructions}</p><textarea className="form-input" rows={8} value={code} onChange={e => setCode(e.target.value)} /><button className="btn" onClick={() => setRun(code)}>Run JavaScript</button>{run && <iframe title="Isolated coding practice" sandbox="allow-scripts" srcDoc={codingDocument(run)} />}</>}
    {['simulation', 'virtual_lab', 'game'].includes(a.type) && <><p>{c.instructions}</p><a href={c.url} target="_blank" rel="noreferrer">Open interactive resource (internet required)</a><iframe title={a.title} src={navigator.onLine ? c.url : undefined} sandbox="allow-scripts allow-forms" referrerPolicy="no-referrer" style={{ width: '100%', height: 350 }} /></>}
  </article>;
}
export default function LearningActivities({ activities = [] }) { return activities.map(a => <Activity key={a._id} activity={a} />); }
