import { useEffect, useState } from 'react';
import OfflineCertificates from './OfflineCertificates';
import { session } from '../../api/client';
import { apiRequest } from '../../api/client';
import { offlinePackages, downloadCourse, removePackage, queueCompletion, pendingProgress, syncProgress, saveDraft, loadDraft } from '../../utils/offlineLearning';
import { LessonVideo, ReadingTools, AssignmentDraft } from './LearningReader';
import LearningActivities from './LearningActivities';
function SavedFile({ blob, name }) { const [url, setUrl] = useState(''); useEffect(() => { const u = URL.createObjectURL(blob); setUrl(u); return () => URL.revokeObjectURL(u); }, [blob]); return <a className="btn" href={url} download={name} target="_blank" rel="noreferrer">Open/download {name}</a>; }
export default function OfflineStudy({ onFlash }) {
  const [packages, setPackages] = useState([]), [courses, setCourses] = useState([]), [pending, setPending] = useState([]), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState(''), [draft, setDraft] = useState('');
  async function load() { setPackages(await offlinePackages()); setPending(await pendingProgress()); }
  useEffect(() => { load().catch(e => setError(e.message)); loadDraft('study-notes').then(setDraft).catch(() => {}); if (navigator.onLine) apiRequest('/learning/mine').then(setCourses).catch(e => setError(e.message)); }, []);
  async function run(work) { setBusy(true); setError(''); try { await work(); await load(); } catch (e) { setError(e.message); onFlash(e.message, 'error'); } finally { setBusy(false); setMessage(''); } }
  return <section><h2>Offline Study</h2><p>Download while online, then open saved notes/files here without internet. Progress syncs when you reconnect. Saved access expires after seven days; refresh the download online. Streaming links require internet unless their provider permits a file download.</p>
    {error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}<p>{pending.length} progress update(s) waiting to sync.</p><button className="btn" disabled={busy} onClick={() => run(async () => { const results = await syncProgress(); const blocked = results.filter(r => r.status === 'blocked'); if (blocked.length) setError(blocked.map(r => r.message).join('\n')); else onFlash('Progress synchronized.', 'success'); })}>Sync now</button>
    <h3>Available courses</h3>{courses.map(c => <p key={c._id}>{c.title} <button className="btn" disabled={busy} onClick={() => run(async () => { const pack = await downloadCourse(c._id, setMessage); onFlash(pack.warnings.length ? 'Notes saved; some linked files could not be downloaded. See package warnings.' : 'Course saved for offline study.', 'success'); })}>Download/refresh</button></p>)}
    <h3>Saved courses</h3>{!packages.length && <p>No courses downloaded yet.</p>}{packages.map(p => <article className="dash-card" key={p.key} style={{ padding: 16, marginTop: 12 }}><h3>{p.course.title}</h3><button className="btn" onClick={() => run(() => removePackage(p.course._id))} disabled={busy}>Remove download</button>
      {new Date(p.expiresAt) < new Date() ? <p>Download expired. Connect and refresh before opening.</p> : <>{p.warnings?.length > 0 && <details><summary>Files requiring internet / download warnings</summary>{p.warnings.map((w, i) => <p key={i}>{w}</p>)}</details>}{p.lessons.map(l => <details key={l._id}><summary>{l.title}</summary><ReadingTools text={l.content}><p style={{ whiteSpace: 'pre-wrap' }}>{l.content}</p></ReadingTools><LessonVideo lesson={l} canTrack={p.canComplete} files={p.files} />{l.resources?.map(r => <p key={r.url}>{p.files[r.url] ? <SavedFile blob={p.files[r.url]} name={r.name || 'resource'} /> : `${r.name}: not available offline`}</p>)}{l.videoUrl && p.files[l.videoUrl] && <SavedFile blob={p.files[l.videoUrl]} name="lesson-video" />}{l.deck?.slides.map((s, i) => <div key={i}><h4>{s.title}</h4>{s.bullets?.map((b, n) => <p key={n}>{b}</p>)}{s.imageUrl && p.files[s.imageUrl] && <SavedFile blob={p.files[s.imageUrl]} name={`slide-${i + 1}-image`} />}</div>)}<LearningActivities activities={p.activities.filter(a => a.lesson === l._id)} /><button className="btn" disabled={busy || !p.canComplete} onClick={() => run(async () => { await queueCompletion(l); onFlash('Completion saved on this device. It will be verified when online.', 'success'); if (navigator.onLine) await syncProgress(); })}>Mark complete</button></details>)}{p.assignments?.map(a => <AssignmentDraft key={a._id} assignment={a} />)}</>}
    </article>)}{session.getUser()?.roles?.includes('student') && <OfflineCertificates />}<h3>Offline study draft</h3><textarea className="form-input" rows={6} value={draft} onChange={e => { setDraft(e.target.value); saveDraft('study-notes', e.target.value).catch(e => setError(e.message)); }} /><p>Drafts are stored for this account on this device. Sign-out removes saved learning data.</p>
  </section>;
}
